apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lan-ips
  namespace: metallb-system
spec:
  addresses:
  - 192.168.2.200-192.168.1.250  # Reserved range for LoadBalancer IPs
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lan-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - lan-ips
