
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tempo

# resources:

helmCharts:
- name: tempo
  version: 1.18.0
  repo: https://grafana.github.io/helm-charts
  valuesFile: values.yaml
  namespace: tempo
  releaseName: monitoring
