apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: charts/secrets/kubeseal/overlays/prod
    target:
      kind: Application
      name: kubeseal
