keys:
  - &temujin age185adlvtqjy4vur45tnvh84ypvq78u5e4zle970vmexwugd8tt5xs592sgk
  # TODO: make a new one
  # - &subutai age185adlvtqjy4vur45tnvh84ypvq78u5e4zle970vmexwugd8tt5xs592sgk
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|sops)$
    key_groups:
      - age:
        - *temujin
       # - *subutai
