apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - secrets

helmCharts:
  - name: bitnami/external-dns
    version: 8.7.2
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml
    namespace: external-dns
    releaseName: support
