apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

# resources:
#   - secrets # applied manually

helmCharts:
  - name: external-dns
    version: 1.15.2
    repo: https://kubernetes-sigs.github.io/external-dns/
    # repo: oci://registry-1.docker.io/bitnamicharts
    valuesFile: values.yaml
    namespace: external-dns
    releaseName: support
