apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - secrets

helmCharts:
  - name: external-dns
    version: 8.7.3
    repo: oci://registry-1.docker.io/bitnamicharts
    valuesFile: values.yaml
    namespace: external-dns
    releaseName: support
