apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: externaldns

resources:
  - secrets

helmCharts:
  - name: external-dns
    version: 8.3.12
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml
    namespace: external-dns
    releaseName: support
