apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml # ArgoCD installation
  - ../../base

patchesStrategicMerge:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: argocd-cm
    data:
      kustomize.buildOptions: --enable-alpha-plugins --enable-helm --load-restrictor LoadRestrictionsNone

patches:
# branch
  - patch: |-
      - op: replace
        path: /spec/source/targetRevision
        value: main
    target:
      kind: Application
      name: .*
  # argocd
  - patch: |-
      - op: add
        path: /data
        value:
          kustomize.buildOptions: --enable-alpha-plugins --enable-helm --load-restrictor LoadRestrictionsNone
    target:
      kind: ConfigMap
      name: argocd-cm
  - patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
    target:
      kind: Service
      name: argocd-server
  # apps
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: argocd/apps/secrets/overlays/prod
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
    target:
      kind: Application
      name: application-secrets
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: argocd/apps/secrets/overlays/prod
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
    target:
      kind: Application
      name: application-services
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: argocd/apps/support/overlays/prod
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
    target:
      kind: Application
      name: application-support
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: argocd/overlays/prod
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
    target:
      kind: Application
      name: application-root
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: argocd/overlays/prod
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
    target:
      kind: Application
      name: application-projects
