# https://kind.sigs.k8s.io/docs/user/configuration/
# kind: Cluster
# apiVersion: kind.x-k8s.io/v1alpha4
# name: infrastructure-professional-website
# nodes:
#   - role: control-plane
#   - role: worker
#   - role: worker
#   - role: worker
---
# Creates a kind cluster with a registry.
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
kindV1Alpha4Cluster:
  name: infrastructure
  nodes:
    - role: control-plane
    - role: worker
    - role: worker
    - role: worker
