apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus-graphana

helmCharts:
- name: kube-prometheus-stack
  version: 68.4.4
  repo: https://prometheus-community.github.io/helm-charts
  valuesFile: values.yaml
  releaseName: monitoring
