## Default values for prometheus/graphana
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.
## Install Prometheus Operator CRDs
##

prometheusOperator:
  admissionWebhooks:
    enabled: true      # Enable webhook
    patch:
      enabled: true    # Auto-generate TLS certificates
    serviceAccount:
      create: true
