---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgAxRPDPcZfNdt1TXDfTnjvC8IK2Od6IbQw+vl4JMgHEb9GflBA0yvHzY0hOBe63bQbtnlWWE3SuAxOrH7Dxh1btwoE7P373zM51zFiUWqpFHAI963nJvIXLmFj81PD+OOjgvVciwOmFr11nDTuxysS/KL5/nmqi1Syz0gTr/B4gFubDwq+FkValp3laHDo4XIPt5+Qt1TiweUgJowGNgGMFB91UBcuKUh1IVKhjxeTz8lszU1TQmsNpwmxnL0x3tWWaBtyqWU9f3yfoJOMDhe1f26TwO7DCH1ZWUeXqUnOBoamWRYLhsGzCa42fCiJGttSbdpDtMQEm8tFI/RKt8enZ5hXBHIk9k0WkD4bhwnrKuOAiK1yn4R5sxd7bWIn3uX2aIoldpTWNCXSQniH4vVUPtCIw3+55rkKRNmIqUtn4zMtBXdlXmvv2KLC+Y21QP7wux6/+WRuJ1sxyemYIY+VObu0c8zXrG25ZbxLyDEmkZ61niuYuS8FZCoq6cHD+gAWwrNqJwwtp4EBBu0trWwrKx44K9gk1E8K+js72RTTd85R8/n4/g3WOAixrZTKLl8q2r8mxEh4hiP6fYvdxhE5dQEfYVxf94IDrK4WDTFN0+YDp/1rMeaBqW8b2oAOPKYzkFytqYMhR7VWZ/6PHow00RIu6lyLvCIfSOtg0LYVgeK3gkeUvvKg9WGS0XjY32uSa5PvTziYYtu2hcQ==
    nextcloud-username: AgB2tXspU4TJxTiQSXkJfVmp8ZWKoVRrv09zFeUeXIaGoZqtJO9eVR2qle0d9L0bg0v6ke1pBMB27ttj7PYoT+P75CZQnyKliEZpfrgCHA17XZGadHELL9m8MrRYg88Bac45mRMfYVRMz2URcJpt9LaL5FZ7FmpJX2tA28c4prZeGP7PomQ2m98XXR0w2S8WeJznAKd94K4R+ZWWNcvpzAeKhUVeAJhOLYKEbs7JEVIP/WS5M45Aondb2Gs2xoUyfU+I4MUJBtdkEwvrRyjImsiZT5YsBI+XuZgz9dhBAtS1VaGyLQvFmSlIgJaugIZj/tx/x/xemCB6bdVgD/B5o3BQKE69X4ewkzExF0Idv8WWzaQazHDJVRdQ+ZRqSpYTJRympDDndLwVQuHSGVi8R7Gypl5OqZeyEaCXvZ7AsEpwpKEY7PgaWUib2Ene76QZgCkieAloqSRWiiVwknzLcKp3+rF40KnonUzGP26KNWCYXOzSzwbFk+HqIr690Wtylt9SFjhV10zNB9aJ35fif2b/AjPI/gNeBU71lhDAMhjGoBhZeFwn5XvsVNIV0XhOcW/oh6fAhAcU+e6CwNv2sOW89zzQlmxsqUdifpAJZdbHkgd4JERgBtf+uP1kgPusw/g74uhWVpRz7xaxYZPNqXmePGgnGAHMJfJiuj8q4MKqi/3QdzI8nHQjbNI6+p3imo8TgAdxKe4=
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud
      namespace: nextcloud
