---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgA84SaRDzKV0yGuw5yKCVjZg6G17nCpHSu86B1uZdcwNTA3NLZBJb6nlHlSWCVbKkO8IialheYiZ6GXFe5+4bYlMz9YzwEKS+ppkjZxyYOYN5u1f5hDqq/KK5P8qvcg1T5pT5JxS5hL/bOFoMXADQ2OjyMpPHNrmAQ/etVCzGa8qCG5DILzqBHDwRohhtohwB318pIwRpBFunodF/kmVOzOzFRHPfNU6G/+pLnvNHtA5l6FJoi0IiK1QxAeEXbZXCTAc8ZWFxRrYJXUTHPBMnPcyOi8/ujvdpPyNurPD8rUeecRW5TXIbAYeQfDpipDp3vd0atF6bFskcLBAjcOdgxXZBNt0iFiCFizJHD/aLRMuvIDBFzwAPRxr9aFD6XJfLJ3dwPy5qDP9yQqGJ8RqphDmJJ2QoWOnUC6K318S8ZaKNhJdtqpcVaIfBUci2owp6bJO6WBHndQ89DET2dm+y6kIgSnnArzHuCgXJoeO1UdOxhre83PzW6SydhKfRFudyNYNA7p58UIvc1+Pmt0PxmIreYZeVwXjlee9+NKPJOIDJZnWIp+fNOMjLHVLVceXZmvs57H9zZ9SlDWGWEAuLn4z97CcVTt2pi8SrqSvMMsOM9OLCzpMJqtPk3irV/ZkR9CTwwohRWdDQiLvxaciSM/2P6yJ+wH58KtasgvzwG8BXaUUn8vZMHWswLgdWfHqnxmuuAZbSDjtYix8g==
    nextcloud-username: AgAs1WCqnEemRfHw8OCQvpEyKmfL0aSVQD0VyMsAKWA56WCs1mR5CYV1LEOC2koUNrlv+TrWRmw7Sz684GxP3jndeSAfhH6NXIRGT2aUgrmYfb6qptRRRR/XOujVr1c2cdqHdkPE4CY2+qwTgYQhUF1zL5tzW2LRHCwjwLX2/uWIzxrq24RQlKURCILBzjRFnRZJ5ruBD34c00/p9f0epdL+28riGrm4/2R29OP7GNkOkW+d0UYNx4StxCyoFVv6MlO3EyjiMYXlklSDpYvVy8R+C1hiVWq7msY8L5oGBmlB6/S+RteIZRDx/icHLilOizrEmZAXxkz8mFf2h3PtIxNaPt4s+uzdU4S7R1gByiw2z+fwkm92ZhJ28Pg/odxNPzljfimMkU7d1hE7P1S/QyuL0h+fYjunVozPikOn//st3/FO2EJPr1AguDNmd75MFJ6UCjfQVDmw+FC8KA08ojR6HXzn5lpXCAdrXwQcuxuED6StvhVQWQ47Wo1AarpoPCpwFfi9X46/fNF+rurlxqHzaC0Rne8WUZy9Db/2gI7uRWb/sa6SwglmfoqtSpOnBrfgR9py5AW1ZbyU5bihUoL9PNU6XLL7DR+0bVrCSd6hgqZzU2xSeoiV6MbdzUqRq4iOqbktE3oE7Rs4wwtNQCC/K2+hbfkIAvfvtyRSdmKB6Uz+GPD7Ovmh36FD2wzr7xmBTVey4n8=
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud
      namespace: nextcloud
