---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgACqdUEeLbZ4bu1popTtRZZlY3Bn4/xMWnr7VFSDr8PBy3qX4Ru6Xn48xSTVz3MarLgUNlSsDLwEOTjp1qu4RP4AKoZsVB1lS6qnm0mwCZpqotgNN9P3eZOOM2ruyGv4/6yQtgWEZauwUmQsETWp55ovzcgugpzIKQVhyXgeVjtLfx2rRTNt1UDAf6vkkva47CrECJAcvIspZqHu1w7q8xzbUNO3iu9pAJulrTe9paQ+lmTfc5EcF+dYpZ2x4wnC8r/YgEZBFwYvVxrSElWJ9ofqYtcSXbbU2XYMq+jSNmcQbdnP2qFdhVuafO2+Dr0gWQSrgzvCpTrCUrUHtlNvK5RQnnmf798nhKCrawkw2mB9UD6oREYRq7Ao2BbJHKbzCi9F3TV/hU9KpN6jU1oCD3QgivtmdUH0gJg/n4gnkC+InIRldAusNoxzte8QngFsZ3ZbmpeDTLKabfRSyCqyk4l0fsz0rKo7jwqn9ixtGocKoOl1aIyHohsnQFC1wjxfGWZZAQjG6ESAzY44w/pBKkKVv7DjZG4/dRqto6gnGCcl35wIUXNS2cRKdHVPy2fR7ZNWKzza+2Eoc68rBQq5/JYueJRbaKdZkvVzB9/HVm7r83TkdoK65qKV2uyZ1KYbYphp2JtJEKLkmBQuv6MFkEXHxVUsRnkdwggnN0OBgJTLAsoPqfHF4Aud1PkrPaonDhcZo3SMWM7c5y27w==
    nextcloud-username: AgAJJAjGGaOBGDSVSNc/wS6muv7RIfH3JGiXqBuJdnVuCeD5+5GvTEA5UmclrHDJwGk3CjWYfTW6tRmfIsOkPdtWZe2qEXGIUd2OiiaZTXZg5nePiNOGsZVEW5UDBDCA2S8+jcUoWLe8lb22w8NSbt3abS8PkbVsHVmK9S6BpOBZLOH69TWc3QbmGKhVnacdtfD5Qz9Ekfy7a0YCBYqSsdOpN3wGlwPzpnKKPM1EXkqe0JUQWzaExTez7lrxXA7+CwAEmKnBvxStdj6bmyrrXSE+PNy7j95w+9q4aAe+OtNpP/xIxVaGIC/BdYy1YGnjKVefgqNWT6TWnHn5bFilFq85NERnRukFr9gUYW4Z6Tn7t4Ujwp6W0C2Je0QzS8z0yD8EYOm0uDK7f5KkWUVJHs/oPNLlEwVWzFn2bmsIpRwlTT32A0xP5XMWR+nlNyjWQrKsU9xY7iGf0jyfiPttOIcvKCdAgBTfvyElP3VP5I0G9r3PQ2BFE4rlRgjhYgGgK+ffzsWZkD5/gvXGmPxaaJL74RFtxhNxVt/0GuZQigos44RvBWMFMSN+Fg/ze04SP6vLjjpiSnETuVqKdIaiE6AxIMmiy5lIm9sSw4317w2dizDz6nG9mqRRz5EAlLetGFEJxV81wyEVEKfNyWyXkM3QIm/DSorirIxifMmJylAL6tRRfh/4exsqFGqP7tHEF61+ZFT15tE=
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud
      namespace: nextcloud
