apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-dns.yaml
  - cert-manager.yaml
  # - coredns.yaml
  - local-path-provisioner.yaml
  - harbor.yaml
  - keel.yaml
  - lpp.yaml
  # - secrets
