apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: local-path-provisioner
    server: https://kubernetes.default.svc
  project: support
  source:
    ignoreMissingValueFiles: true
    chart: containeroo/local-path-provisioner
    repoURL: https://charts.containeroo.ch
    targetRevision: 0.0.31
    # helm:
    #   values: |
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
