apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitea

helmCharts:
  - name: gitlab
    version: 8.8.0
    repo: http://charts.gitlab.io/
    valuesFile: values.yaml
    namespace: gitlab
    releaseName: services
