apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: factorio-vanilla

resources:
  - namespace.yaml
  - secrets

helmCharts:
  - name: factorio-server-charts
    version: 2.1.0
    repo: https://sqljames.github.io/factorio-server-charts/
    valuesFile: values.yaml
    namespace: factorio-vanilla
    releaseName: vanilla
