## Compute Resources required by the operator container
resources:
  ## We have to ensure that factorio have enough computing resources avaiable. We set here an absolute minimum
  ## Keep in mind that big factorio base can consume a lot of memory and cpu
  requests:
    memory: 3Gi
    cpu: 1500m
  ## If you like to limit factiorio resources
  limits: {}
  # limits:
  #   memory: 1024Mi
  #   cpu: 1000m

## @section Port-Fixer Parameters
## @param port_fixer.enabled Enable the Factorio Port Fixer
## @param image.repository Factorio port-fixer image repository
## @param image.tag Factorio port fixer image tag (immutable tags are recommended)
## @param image.pullPolicy Factorio port fixer image pull policy
## @param image.port Factorio port to announce via port-fixer, defaults to service.port
port_fixer:
  # Adds an extra container that tries to help with connection issues via the public server browser.
  # This is especially useful when you can’t set up outgoing static port mappings and see log messages like these:
  # > Warning ServerRouter.cpp:541: Received own address message reply with conflicting address (got IP ADDR:({<ip>:19296}), expected IP ADDR:({<ip>:58037}))
  # > Warning ServerMultiplayerManager.cpp:651: Determining own address has failed. Best guess: IP ADDR:({<ip>:58037})
  # > Warning ServerRouter.cpp:541: Received own address message reply with conflicting address (got IP ADDR:({<ip>:19297}), expected IP ADDR:({<ip>:58037}))
  # > Warning ServerRouter.cpp:541: Received own address message reply with conflicting address (got IP ADDR:({<ip>:24105}), expected IP ADDR:({<ip>:58037}))
  # Note: Port forwarding for incoming traffic still needs to be set up properly for this to work.
  # For more info, check out:
  #   - https://github.com/SQLJames/factorio-server-charts/issues/15
  enabled: true
  image:
    repository: "ghcr.io/zcube/factorio-port-fixer"
    pullPolicy: Always
    tag: latest
  port: ''
#### Persistence Configuration ####
## @section Persistence Configuration
## @param persistence.enabled Enable persistence using Persistent Volume Claims
## @param persistence.dataDir.Size Persistent Volume size
## @extra persistence.dataDir.existingClaim The name of an existing PVC to use for persistence
## @param persistence.storageClassName Persistent Volume storage class
## @param persistence.annotations Persistent Volume Claim annotations
## @param persistence.labels Persistent Volume Claim labels
## Sets the data persistence volume configuration
## IMPORTANT: If you do not setup a PV all your savegames will be lost on pod recreation or helm upgrade
persistence:
  enabled: true
  dataDir:
    Size: "1Gi"
    ## If you have an existing claim, set your name here
    # existingClaim: "existing-claim-name"
  ## If you like to use a specific storageClassName, set the name. Leave it blank for the default class
  storageClassName: "local-path"
  ## If you have annotations to spin up a PV i.e. the location. Remove the curly braces
  annotations: {}
  ## If you have additional labels to apply to the volume
  labels: {}

## @param factorioServer.save_name Factorio save name
## @param factorioServer.generate_new_save Generate a new save if `save_name` is not found
## @param factorioServer.update_mods_on_start Update mods on server start
## @param factorioServer.load_latest_save Lets the game know if you want to load the latest save
## @param factorioServer.port Factorio Game Server port
## @param factorioServer.rcon_port Factorio Server RCON port
## @param factorioServer.env Additional environment values for the Factorio Server container
factorioServer:
  # name to use for the save file
  save_name: "vanilla"
  # generate a new save if one does not exist before starting the server
  generate_new_save: true
  # if mods should be updated before starting the server
  update_mods_on_start: false
  # load latest when true. Otherwise load SAVE_NAME
  load_latest_save: true
  # enables or disables the mods for DLC Space Age in mod-list.json
  enable_space_age: true
  # factorio game server port
  # the default game port (34197) has been changed to 31497 to resolve issues when using the port-fixer.
  # this port setting is typically for internal Kubernetes configuration only, and in most cases, it does not need to be modified.
  # if it is necessary to change the game server port where you connect to the game, update the "service.port" value accordingly.
  port: 31497
  # factorio game rcon port
  # this port setting is typically for internal Kubernetes configuration only, and in most cases, it does not need to be modified.
  # if it is necessary to change the rcon server port where you connect to it, update the "rcon.port" value accordingly.
  rcon_port: 27015
  # adding addtional environment variables to the factorio server container
  env: {}
    # - name: MY_VAR
    #   value: "my_value"

## @param account.accountSecret Existing secret containing a valid factorio.com username and either a password or a token (or both)
## @param account.username Factorio.com username, ignored if `account.accountSecret` is set
## @param account.password Factorio.com password, ignored if `account.accountSecret` is set
## @param account.token Factorio.com token, ignored if `account.accountSecret` is set
account:
  # Existing secret containing a valid factorio.com username and either a password or a token
  # Example:
  #
  # apiVersion: v1
  # kind: Secret
  # metadata:
  #   name: account-secret
  # data:
  #   username: <username in base64>
  #   password: <password in base64>
  #
  # accountSecret: account-secret
  accountSecret: "vanilla-factorio-secret"
  # Your factorio.com login credentials. Required for games with visibility public
  username: "VanofHoogen"
  # password: ''
  # Authentication token. May be used instead of password above.
  #  token: ''

## @param serverPassword.passwordSecret Existing Secret containing a `game_password` data entry
## @param serverPassword.game_password Password required to log into the factorio server. Ignored if `serverPassword.passwordSecret` is set
serverPassword:
  # password required to log into the factorio server
  # game_password: ''
  # Existing Secret containing a `game_password` data entry
  passwordSecret: "vanilla-factorio-secret"

## @param server_settings.name Factorio server name
## @param server_settings.description Factorio server description
## @param server_settings.tags Factorio server tags
## @param server_settings.max_players Maximum number of players allowed, admins can join even a full server. 0 means unlimited
## @param server_settings.visibility.public Publish the server on the official Factorio matching server
## @param server_settings.visibility.lan Server will be visible in LAN
## @param server_settings.require_user_verification When set to true, the server will only allow clients that have a valid Factorio.com account
## @param server_settings.max_upload_in_kilobytes_per_second Optional, default value is 0. 0 means unlimited
## @param server_settings.max_upload_slots Optional, default value is 5. 0 means unlimited
## @param server_settings.minimum_latency_in_ticks Optional, one tick is 16ms in default speed, default value is 0. 0 means no minimum
## @param server_settings.ignore_player_limit_for_returning_players Players that played on this map already can join even when the max player limit is reached
## @param server_settings.allow_commands Possible values are true, false and admins-only
## @param server_settings.autosave_interval Autosave interval in minutes
## @param server_settings.autosave_slots Server autosave slots, it is cycled through when the server autosaves
## @param server_settings.afk_autokick_interval How many minutes must pass before someone is kicked when doing nothing, 0 for never
## @param server_settings.auto_pause Whether the server should be paused when no players are present
## @param server_settings.auto_pause_when_players_connect Whether should the server be paused when someone is connecting to the server.
## @param server_settings.only_admins_can_pause_the_game Specifies if anyone can pause or only admins
## @param server_settings.autosave_only_on_server Whether autosaves should be performed only on the server or also on all connected clients. Default is true
## @param server_settings.non_blocking_saving Highly experimental feature, enable only at your own risk
## @param server_settings.max_heartbeats_per_second Network tick rate. Maximum rate game updates packets are sent at before bundling them together. Minimum value is 6, maximum value is 240.
## @param server_settings.minimum_segment_size Minimum network messages segment size
## @param server_settings.minimum_segment_size_peer_count Minimum network messages segment count
## @param server_settings.maximum_segment_size Maximum network messages segment size
## @param server_settings.maximum_segment_size_peer_count Minimum network messages segment count
server_settings:
  # Your Instance Name
  name: "[k3s] helm-kubernetes-argocd-vanilla"
  # Your Instance Description
  description: "Factorio running on Kubernetes"
  tags:
  - vanilla
  - helm
  - experimental
  # Maximum number of players allowed, admins can join even a full server. 0 means unlimited.
  max_players: 0
  # Game visibility
  visibility:
    # Game will be published on the official Factorio matching server
    public: true
    # Game will be broadcast on LAN
    lan: true

  # When set to true, the server will only allow clients that have a valid Factorio.com account
  require_user_verification: true
  # optional, default value is 0. 0 means unlimited.
  max_upload_in_kilobytes_per_second: 0
  # optional, default value is 5. 0 means unlimited.
  max_upload_slots: 5
  # optional one tick is 16ms in default speed, default value is 0. 0 means no minimum.
  minimum_latency_in_ticks: 0
  # Players that played on this map already can join even when the max player limit was reached.
  ignore_player_limit_for_returning_players: false
  # possible values are, true, false and admins-only
  allow_commands: admins-only
  # Autosave interval in minutes
  autosave_interval: 10
  # server autosave slots, it is cycled through when the server autosaves.
  autosave_slots: 5
  # How many minutes until someone is kicked when doing nothing, 0 for never.
  afk_autokick_interval: 0
  # Whether should the server be paused when no players are present.
  auto_pause: true
  # Whether should the server be paused when someone is connecting to the server.
  auto_pause_when_players_connect: false
  # specifies if anyone can pause or only admins
  only_admins_can_pause_the_game: true
  # Whether autosaves should be saved only on server or also on all connected clients. Default is true.
  autosave_only_on_server: true
  #  Highly experimental feature, enable only at your own
  #  risk of losing your saves. On UNIX systems, server will fork itself to create an
  #  autosave. Autosaving on connected Windows clients will be disabled regardless of
  #  autosave_only_on_server option.
  non_blocking_saving: false
  # Network tick rate. Maximum rate game updates packets are sent at before bundling them together.
  # Minimum value is 6, maximum value is 240.
  max_heartbeats_per_second: 60
  #  Long network messages are split into segments that are sent
  #  over multiple ticks. Their size depends on the number of peers currently connected.
  #  Increasing the segment size will increase upload bandwidth requirement for the server
  #  and download bandwidth requirement for clients. This setting only affects server
  #  outbound messages. Changing these settings can have a negative impact on connection
  #  stability for some clients.
  minimum_segment_size: 25
  minimum_segment_size_peer_count: 20
  maximum_segment_size: 100
  maximum_segment_size_peer_count: 10
