# tasks file for doots
- name: Pinging localhost
  ansible.builtin.ping:

- name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
  ansible.builtin.include_vars:
    file: main.yml
    name: software

- name: Installing modern unix tools
  become: true
  become_method: sudo
  ansible.builtin.package:
    name: "{{ software.modern_unix }}"
    state: latest
  with_items: "{{ software }}"

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: software.python_packages

- name: Installing global npm dependencies.
  community.general.npm:
    global: true
    name: "{{ software.node_packages }}"
  with_items: "{{ software }}"
# Node
- name: Installing global npm dependencies.
  community.general.npm:
    global: true
    name: "{{ software.node_packages }}"
  with_items: "{{ software }}"
# python
- name: Install Python packages
  ansible.builtin.pip:
    name: "{{ software.python_packages }}"
  with_items: "{{ software }}"
