---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: factorio
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - namespace.yaml
  # - ingress.yaml
  - persistentvolumeclaim.yaml
