---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: factorio-pvc
  labels:
    app.kubernetes.io/component: game
    app.kubernetes.io/instance: factorio
    app.kubernetes.io/name: factorio
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
