apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: externaldns

# resources:
#   - secrets

helmCharts:
  - name: coredns
    version: 1.37.1
    repo: https://coredns.github.io/helm
    valuesFile: values.yaml
    namespace: coredns
    releaseName: support
