# Default values for coredns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

servers:
  - zones:
      - zone: .
    port: 53
    plugins:
      - name: forward
        parameters: ". 192.168.1.152"
