apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harbor

resources:
  - storageClass.yaml

helmCharts:
  - name: harbor
    version: 1.16.1
    repo: https://helm.goharbor.io
    valuesFile: values.yaml
    namespace: harbor
    releaseName: support
