apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smb
resources:
  - secrets


helmCharts:
  - name: csi-driver-smb
    version: 1.17.0
    repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
    valuesFile: values.yaml
    namespace: smb
    releaseName: support
