apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-shared-storage-pv
  annotations:
    helm.sh/resource-policy: Delete
  labels:
    app.kubernetes.io/instance: gitea
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  hostPath:
    path: "/data/gitea/shared-storage"
  # claimRef:
  #   namespace: gitea
  #   name: gitea-shared-storage
