apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-shared-storage-pv
  annotations:
    helm.sh/resource-policy: Delete # Changed to 'delete' to clean up automatically if necessary
  labels:
    app.kubernetes.io/instance: gitea
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete # Updated to 'Delete' for automatic cleanup
  volumeMode: Filesystem
  hostPath:
    path: "/data/git"
    # path: "/data/gitea/shared-storage"
  claimRef:
    namespace: gitea
    name: gitea-shared-storage
