apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-shared-storage-pv
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/instance: gitea
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: "/data/gitea"
  claimRef:
    namespace: gitea
    name: gitea-shared-storage
