apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-shared-storage-pv
  annotations:
    helm.sh/resource-policy: delete # Changed to 'delete' to clean up automatically if necessary
  labels:
    app.kubernetes.io/instance: gitea
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete # Updated to 'Delete' for automatic cleanup
  volumeMode: Filesystem
  hostPath:
    path: "/data/gitea/shared-storage" # Ensure this matches the correct path on the host
  claimRef:
    namespace: gitea
    name: gitea-shared-storage
