apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: charts/support/external-dns/overlays/prod
    target:
      kind: Application
      name: external-dns
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: charts/support/cert-manager/overlays/prod
    target:
      kind: Application
      name: cert-manager
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: charts/support/keel/overlays/prod
    target:
      kind: Application
      name: keel 
