apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
      - op: replace
        path: /spec/source/path
        value: nix-k8s-homelab/charts/support/external-dns/overlays/prod
    target:
      kind: Application
      name: external-dns
  - patch: |-
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
      - op: replace
        path: /spec/source/path
        value: nix-k8s-homelab/charts/support/lpp/overlays/prod
    target:
      kind: Application
      name: local-path-provisioner
  - patch: |-
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
      - op: replace
        path: /spec/source/path
        value: nix-k8s-homelab/charts/support/cert-manager/overlays/prod
    target:
      kind: Application
      name: cert-manager
  - patch: |-
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
      - op: replace
        path: /spec/source/path
        value: nix-k8s-homelab/charts/support/harbor/overlays/prod
    target:
      kind: Application
      name: harbor
  - patch: |-
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
      - op: replace
        path: /spec/source/path
        value: nix-k8s-homelab/charts/support/keel/overlays/prod
    target:
      kind: Application
      name: keel
  - patch: |-
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
      - op: replace
        path: /spec/source/path
        value: nix-k8s-homelab/charts/support/coredns/overlays/prod
    target:
      kind: Application
      name: coredns
  - patch: |-
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
      - op: replace
        path: /spec/source/path
        value: nix-k8s-homelab/charts/support/lpp/overlays/prod
    target:
      kind: Application
      name: local-path-provisioner.yaml
