* Chinese

** Table of Content
** Full sentences
为什么你自己去拿 why did you take it yourself?
我丢了好塑胶在垃圾桶 I threw plastic in the trash

** Dictionary
*** International units
公斤 gong1jin1 kg
公里 gong1li3 kilometer
*** Computer/science
文本编辑器 wen2ben1 bian1ji2 qi4 test editor
电脑程序 dian4nao3 cheng2xu4 computer program
微控制器 wei1 kong4zhi4 qi4 microcontroller
3D打印机  da1yin4ji1 3d printer
*** Action verb
坏了 huai4le broke
拿 na2 take
丢 diu1 toss
修理/修补 xiu1li3/xiu1bu3 repair
被打 bei4da3 beaten (physically)
*** Adjectives
坏 huai4 bad
强大 qiang2da4 powerful
相关 xiang1guan1 relevant
普通 pu3tong1 local
受欢迎 shou4 huan1ying2 popular
好笑 hao3xiao4 funny
*** Money
省钱 sheng3qian2 save money
*** Business
客户 ke4nu4 client
开除 kai1chu2 fired/explusion
*** Relationships
丈夫 zhang4fu1 husband
妻子 qi1zi wife
妻夫 qi1fu1 husband and wife
*** Crime
(v) 偷吃 tou1chi1 steal (food)
偷用 tou1yong4 steal
*** sport
球赛 qiu2sai4 match
篮球 lan2qiu2 basketball
*** Usefull patterns
一半百年 yiban4 bai1nian2 half a century
*** Frequency
*** Material
塑胶 su4 jiao1 plastic
*** Savyings
看什么看 kan4shen2me kan what are you looking at?
笑什么笑 xiao4 shen2me xiao4 what you laughing at?
*** School
作业 zuo4ye4 homework
*** Body
手臂 shou3bi4 arm
脚 jiao3 foot
手 shou3 hand
*** Unk
这件事 zhe4 jian4 shi4 this matter

**  Often missed chars
睡觉 shuijiao sleep
休息 xiuxi rest
读 du2 read
最近 zui4jin4 recently
情况 qing2kuang4 situation/circumstances

** Patterns
百分之。。。 for example 百分之20人 20% of people

** Sayings...
你有别的吗？you have an another one?

** 22日/02月/2023年
*** sentences
我几天以前开始用第三次老板的3D打印机
我现在用一个Raspberry pi为控制器对它
可是我现在有两大的问题。
第一个问题这个3D打印机打印不好基本上我必须修修补补跟多。
第二个问题我的raspberry Pi控制器不可能套或与3D打印机。
所以现在我不印机跟多自从1个公斤成本三十块左右
我的文本编辑器一些天以前坏了然后我更改文本编辑器为更老的而是更强大的
这个文本编辑器叫EMACS被创建在1970年而且一半百年以后这个电脑程序还是相关的
*** linking words
或者 huo4zhe3 or
只要 zhi3yao4 so long as
不关 bu4guan3 regardless of...
而是 re2shi4 but
*** New words
履历表 lv3li4 biao3 resume
3D打印机  da1yin4ji1 3d printer
控制器 kong4zhi4 qi4 controller
微控制器 wei1 kong4zhi4 qi4 microcontroller
印机  yin4ji1 print
坏习惯 huai4 xi2quan4 bad habit
*** Teacher sentences
我休息在我的沙发上 I slep on the couch

** 01日/01月/2023年
我这个星期开始我的工作感觉着了比较生产性的
生产性的 sheng1xhang3 xing4 de productif
事件 shi4jian4 event(s)
第二老板开被除的事件以后也第一老板讨论这个事件于每一个工作人亲自的
老板 lao3ban3 boss
亲自 qing1zi4 personally
也次的时候我试试看新的东西当我应该做比较重要的东西
重要 zhong4yao4 important
例如当这个事件发生了的时候我变化了我的文本编辑器
发生 fa1sheng1 occur
变化 bian4hua4 change
文本编辑器 wenben bian1ji2 qi4 text editor
这个文本编辑器为更老的而是更强大的
强大 qiang2da4 powerful
1978年左右它生去了在MIT的大学
一半百年的修修补补以后使这个电脑程序非常复杂但是非常有用
修修补补 xiuxiu1bubu3 tinker
复杂 fuza

** 07日/02月/2023年
*** Previous week Words
剪头发 jian toufa cut hairs
剪刀 jiandao scissors
剪（v）jian cut/sheer
也许 ye3xu3 maybe
也许以后 ye3xu3 yi3hou4 maybe later
换新的工作 huan4xin1de gong1zuo4 change to a new job
换 huan4 change
新的同时 xin1de tong2shi4 new colleague
总共 zong3gong4 all together/total
我们现在总共有10个人 We have all together 10 people
一年以前比现在更少的工人 a year ago to now we have fewer people
我在。。。读到
读 du2 read
我最近读到开除百分之30的
到少 dao4shao3
省钱 sheng3qian2 save money
而是 ershi but
收 shou1 to receive/to accept
不敢相信 bu4gan3 xiang1xin4 unbelievable
跟着 gen1zhe follow
跟着我 gen1zhe follow me
别人做  bie2 ren2zuo other people do
比较 bi3jiao4 (to compare)
有效率 you3xiao4lv4 efficient
工厂 gongchang factory
回来了 hui2lai2le came back
情况 qing2kuang4 situation/circumstances
升值 sheng1zhi2 appreciation
变成 bian4 cheng2 become
电脑工程的经理
经理 jing1li3 manager
努力工作 nuli gong1zuo4 work hard
聪明 cong1ming2 clever/intelligent
*** Sentences
昨天我尝试过一家餐厅叫酸泡菜在Wharf和Johnson路口
酸泡菜 suan1pao4cai4 sour pickle/kimchi
这家餐厅提供白人舒适的食物
提供 ti2gong1 provides/offer
舒适 shu1shi4 cozy/comfort
他有全天早餐和三明治
全天 quan2tian1 all day
三明治 san1ming1 zhi1 sandwinch (loan word)
这家餐厅的老板是中国人所以他有好喝绿茶而且茉莉花茶
绿茶 lv4cha2 green tea
茉莉花茶 mo4li4hua1 cha2 jasmine tea
总共的经验不错
总共 zong3gong4 all together
下次我会带上我的太太所以她可以常一常
带上 dai4shang4 take/bring on
带下 dai4xia4 take off

** 14日03月2023年
*** Sentences
第个三老板回家以后的时候过对收我《我会离开这个公司然后开始一个公司》
所以我和公司高工程师这个星期工作周转
下个星期二以后我被是中级工程师也这个公司会需要我和电脑技能
几个天以后我会问加薪水
为了我上个周末成为一名中级工程师我不得不学习其他的电脑工
而且这个星期五每一个公司人住在维多利亚都去在温哥华以便加拿大公司人可以看见彼此
像上一次我现在负责办这个聚会
*** new Words
阿根廷 a1gent1ting2  Argentina
周转 zhou1zhuan3 turnove?
中级工程师 zhong1ji2 gong1cheng2shi1 mid-level engineer
技能 ji4neng2 skils (remember the neng)
成为 cheng2wei2 to become
其他 qi2ta1 anothe
不得不 bu4de2bu have to
以便 yi1bian4 so that
彼此 bi3ci3 each other
负责 fu4ze2 in charge (v)
聚会 ju4hui4 party/get together
*** sayings
会需要我 hui4 xu1yao4 wo will need me
像上一次 xiang4 shang4 yi3ci like last time

对不起这个星期我不特别学学习习过
但是我花到时间维修同事的3D打印机
维修 wei2xiu3 repair
3D打印机  da1yin4ji1 3d printer
*** Reminder
3D打印机  da1yin4ji1 3d printer

** 05日04月2023年
*** Sentences
我有大新闻；我在找新的工作。
上个星期四我问我的老板请给加薪
他对我说我现在只能给你提高通货膨胀
开会以后我感觉过背叛
在那个星期二开会的时候我说《我是烧坏所以我要用两请假》
所以我休息了从上个星期三到这个星期二
我一边我休息了一边申请新的工作
西方的人有一个俗语《为什么买这个奶牛当她的牛奶有空》
而且我自己买到一个3D打印机虽然这个打印机的搭建说明非常复杂的
*** Relearned
通货膨胀 tong1huo4 peng4zhang4 inflation
提高 tigao improve
背叛 bei4pan4 betrayed
烧坏 shao1 huai3 burned out ?
请假 qing3jia4 days off
休息了 xiu xile rest(v)
俗语 su2yu3 saying
牛 niu cow
牛奶 niunai milk
奶牛 nainiu milking cow (specific type of cow)
搭建说明 dajian4 shuoming2 building instructions
搭建 da1jian to build (v)
指示 zhi3shi4 instructions
*** Chapter 1; Text 1 review
红叶 hong ye red leaf
著名 zhu4 ming2 famous
这就是 zhe4 jiu4 shi4 this is
放在书里 fang4zai4 shu1li3 put in the book
放在上面桌子 fang4zai4 shang4mian zhuozi put on the table
当书签用 dang shu1qian1 yong use as a bookmark
书签 shu1qian1 bookmark
弄破 nong4po4 break (v)
国家 guo jia nation
特别 tebie especially
东部地区 dongbu4 di4qu Eastern region
南部地区 nan2bu4 di4qu Southern region
欧洲 ou1zhou1 europe
地区 di4qu area/region
漂亮 piao4liang pretty
秋天 qiu tian autumn
漂亮极了 piao4liang jile extremely beautiful
极乐 jile extremely
国旗 guo2qi2 flag
有意思 youyisi interresting
*** Chapter 1; Text 2 review
一片红叶 yi pian hongye one red leaf
朋友们送给她 pengyoumen song gei3 ta friends gave her...
礼物 liwu4 gift
捧着 pengzhi hold
唯一 weiyi only (adv)
就像 jiuxiang like
收下 shou xia accept
感动得差点儿 gangdong3 de cha4dianr
流下了眼泪 liuxiale yan3lei4 shed a tear
笑话 xiao hua joke
小气了 xiaoqi le stingy (bad)
舍不得 she bude reluctant
不这么想 bu4 zheme xiang don't think so
*** Chapter 2; text 1
晚会 wan3hui4 party
参加 can1jia1 join
重要 zhongyao important
那么 na4me that
侄子 zhi2zi nephew
一周岁 yizhou sui4 one year old
全家 quan2jia1 whole family
亲戚 qin1qi1 relative
亲戚朋友 qin1qi1 peng2you3 relatives
祝贺 zhu4he4  celebrate
懂什么呀 dong3 shen2me ya what does (he) know
懂呀 dong3ya understand
呀 ya ahhh (as as 啊)
主角 zhu3jiao3 main character
传统 chuang2tong3 traditional
表演节目 biao3yan3 jie2mu4 show program
电视节目 dian4shi4 jie2mu4 tv show
古代中国 gu3dai4 zhongguo2 ancient China
面前 mianqian front
将来 jiang1lai2 future
或者 huo4zhe3 or
有关 you3guan1 related
抓周 zhua1zhou1 catch of the weel
抓 zhua1 catch/grasp
** 19日04月2023年
*** Sentences
我的堂妹太太的弟弟是乌克兰也选下榻在乌克兰
自从他选下榻在乌克兰他加入乌克兰的军队
他在几天内会去旁边Bakhmut前线
我的堂妹和他的太太一起请问我《如果你可以帮助我们。 我们会买设备为他》
自从我不明白乌克兰文也不知道在哪里买军队的设备我给了他们七百加比 (jiapi)
他们是了感动
我和我的太太路行的时候一起会看见他们
我的堂妹有两个可爱的女儿我只见面一个女儿
我有时候笑话我有家人在每个为生存而战的国家
*** new words
堂妹的弟弟 tang2 mei4dedi4di
堂妹 tang2mei4 cousin
乌克兰 wu1ke4lan2 ukranian
下榻 xia4ta4 to stay (待 better?)
生存 sheng1cun (ts ooh en) survive
而战 er2 zhan4 to fight

*** TODO Forgotten words
选 xuan3 chose
加入 jiaru4
军队 jun dui4 army
在几天内 zai4 jitian1nei4 in a few days
旁边Bakhmut pang2bian bakhmut
前线 qian2xian4 frontline
试试看 shi shi kan try
尝试 chang2shi4 try
帮助 bang zhu help
设备 she4 bei4 equipment
**** previous
意思 yisi interresting
无聊 wuliao boring
当作 dang zuo as
认知 renshi recognize
唯一 wei yi only
捧着 pengzhi hold
就像 jiuxiang like
收下 shou xia accept
笑话 xiao hua joke
小气了 xiaoqi le stingy (bad)
不这么想 bu4 zheme xiang don't think so
就 jiu meaning and usage?
过 guo can be used as a verb to denote celebration
Doubling of adjectives
圆圆的  yuan yuan de round
远远的 yuanyuan de far away

** Forever ago 17日05月2023年
*** Sentences
从开始在哪儿我假期故事
假期 jia4qi1 vacations
在我的太太去过的所有地方她比较喜欢安特卫普
所有 suo3you3 all
在我们去过的所有地方 out of all places we've been
欢安特卫普 an1te4wepu3 antwerp
比利时 bi3li4shi2 belgium
安特卫普比布鲁塞尔更干净的和安静的
布鲁塞尔 bùlǔsài'ěr brussels
干净的 ganjing4 de clean
静的 an1jing4 quiet
那城市还有强的啤酒油腻食物。而且他们不说话法文
强的 qiang2de strong
油腻 you2ni4 greasy
腻 ni4 grease
一般比利时人不说话法文剩下的人不说话荷兰语
剩下 sheng4xia "the rest"
荷兰语 he2lan2 yu3 dutch
当我的太太喜欢伦敦我们别要住在那儿
伦敦 lun dun london
自从法文人最喜欢暴动我们决定不去在巴黎
暴动 bao4dong4 riot
巴黎 ba1 li2 paris
当我们假期在卢森堡我们看见堂弟的家人
卢森堡 lu2sen1bao3
他有最可爱的怒而女儿。她们可以说三个语言

装修 zhuang1xiu renovation
第一层楼 di yi ceng2 lou2 first floor
情况 qing2kuang4 situation

** 19日05月2023年
假期后我们的装修开始紧接
装修
我们雇了一个营造商在我们假期的时候然后他说我们会开始装修一天后你回家
雇了 gu4le
装修 zhuangxiu1 renovation
营造商 ying2zaoshang1 builder
我觉得我的太太不特别喜欢收拾假期到来同一天
假期 jia4qi1 vacations
收拾 shoushhi pack
所以我问我的房子营造商《如果我们开始装修下个天》
装修 zhuangxiu1 renovation
所以下天的时候当我的太太开车的时候我收拾房子第一层楼
收拾 shoushi pack
层楼 cenglou first floor
我面见在网上一个以色列人他最帮助我到我的3D打印机工作
以色列 yi3se4lie4 israel

** 24 05 2023年
我上个漫长周末有到忙的
漫长 mang4chang2 long
我用了我的打印机太多所以我的太太告诉我《请与交建设者在隔音》
da yin ji (printer)
与建设者 yu3 jian4shezhe builder
隔音 ge2yin sound proof
建设者在房子的装修开始的时候告诉我们《他发现一个承重墙在地层楼》
建设者 jian4shezhe builder
装修 zhuangxiu1 renovation
发现 fa xian found
承重墙 cheng2zhong4 qiang load bearing wall
地层楼 di4ceng2lou ground floor
墙 qiang4 wall
土木工程师 tu3mu4 gong1cheng2shi1 civil engineer
土木工程师的计划不显示这个墙在第一层楼作为承重墙
计划 ji4hua2
-  作为 zuo4wei2 as (pattern) did not show this (作为) as that
幸运的是这个土木工程师些天以后来我的家检查这个墙
幸运的是 xing4yun4 se shi fortunately
运气 yunqi luck
检查 jian3cha2 examine/inspect
我和她必须去在她的最好怒朋友婚姻
婚姻 hunyin1 marraige

** 01日06月2023年
*** Sentences
我在活动很少与人关系但是在太太的最好女朋友婚礼前一天我和太太交了新朋友
他也是工作在电脑工程师在Microsoft的工作
他和她的太太一起香港人现在他们住在温哥华
认识他们有很奇怪的自从我们和他们喜欢很多的一样的东西
例如他们喜欢玩电脑游戏和好吃亚洲的食物
他对我说在Microsoft办公室有一些3D打印机
我的太太的最好女朋友婚礼是最可爱事件
上个周末的婚礼在红酒酒厂左右北温哥华到岛。那个酒厂的白酒很好喝也很闪闪发光
*** new
婚礼 hun1li3 wedding
关系 guang1xi4 relationship/connection
办公室 ban4gong1shi4 office
酒厂 jiu3chang3 winery (alcohol factory)
闪闪发光 shan3shan3 faguang1 sparly
** 17-31日05月2023年 recap
   - +[[Table of Content]]
时差一个小时 one hour time difference
时差 shi2cha1 time difference
越来越 yue4lai2yue4 more and more
严重 yan2zhong4 serious
有其他的 you3 qi2ta1 de there are others
其他 qi2ta1 others
这地方有很多食物和其他的东西 this place has food and other things
症状 zheng4zhuang4 symptoms
=继续= ji4xu4 continue
会他 hui4 ta meet him

模式 mo2shi4 mode
大部分 da4bu4fen4 most
文化 wen2hua4 culture
影响 ying3xiang3 influence
收到 shou1dao4 receive
彼此 bi3ci3 each others
绝对不会 jue2dui4 bu4 hui4 absolutely not
绝对 jue2dui4 absolutely
爱国 ai4guo2 patriotic
俄罗斯 e4lui2si1 Russia
失去 shi1u4 lose
有利 you3li4 favorable
有力 you3li4 powerful

时去买新 shi2qu4 mai3xin1 time to buy new
=杂货店= za2huo4 dian4 grocery store
超级市场 chao1ji2 shi4chang3 super market
语音 yu3yin voice
声音 shengying1 sound
发放 fa1fang4 distribute
音乐 yin1ye4
有意思 you3 yi4si interesting
意思 yi4si meaning
=一刻钟= yike4 zhong1 quarter hour
=放轻松= fang4qing1song1 take it easy
停电 ting2dian4 power failure
停 ting2 stop
美食中心 mie3shi2 zhong1xin1 food center
结婚了 jie2hun1le get married
婚礼 hun1li3 wedding
机会难得 ji1hui4 nan2de2 rare opportunity
机会 jihui4 opportunity
价钱 jia4qian2 price
A比B快百分之三百
X倍 () bei4 x times faster
完成 wan2cheng2 finish
团体 tuan2ti3 group
经验 jing1yan4 experience
工作经验 gongzuo4 jingyan4 work experience
你有几年的经验 how many years of experience?

** More recap
音乐 yin1yue4 music
声音 sheng1yin1 voice
声音小一点 lower your voice
发放 fa1 fang4 distribute
意思 yi4si meaning
有意思 you3yi4si1 interresting
放轻松 fang4 qingsong take it easy
一刻张 yike4 zhang1 a moment
一刻钟 yike zhong1 quarter of an hour
停电 ting2dian4 power failure
停电只有一刻钟 power outage was only 15 mins
美食中心 mei3shi2 zhongxin 1 food center/court
食物 shi2wu4 food
结婚 jie2hun marriage
重要 zhongyao4 important
机会 jihui4 opportunity
工作经验 gongzuo jingyan4 work experience
有几年的工作吗 how many years have you worked
价钱 jia4qian2 price
团体 tuan2ti3 group
奶酪 nai3lao4 cheese
动作 dongzuo4 action
水果 shuiguo3 fruits
买菜 mai3cai4 grocery shopping/buy food
方便 fang1bian4 convenient
音乐票 yinyue4 piao4 music ticket
找不到 zhao3bu4dao4 can't find
找不着 zhao4bu4zhao2 can't find

*** often forgotten
一定 yiding for sure
不一定 bu4 yiding uncertain
肯定 ken3ding  certain
确定 queding4 for sure
冬天 dongtian winter
春天 chuntian spring
夏天 xiatian summer
秋天 qiutian autumn

A 之类的 B
这个之类的快 fast like this
我的杯子之类的大 big like my cup

*** Sentences
上个周末我很轻松关于编码也我做不一样的事儿
轻松 qingsong relax
关于 guanyu about
以太网电 yi3tai4 wang3sian4 ethernet
缆 lan3 cable
连接 liang2jie1
我在上个周末完到以太网上缆的连接
切 qie cut
比如你可定买500英尺以太上网缆然后切需要的电缆长度
英尺 ying1chi3 feet (measure)
需要 xu1yao4 need
电缆 dian4lan3 cable (electric)
我有很多附带项目的做
附带 fudai secondary
项目 xiang4mu4 project
我的附带项目做差不多写3一些1网页

** new
yibian pattern
一边我喝咖啡一边我听音乐
一边我玩电脑游戏一边我聊无我的朋友们
liao
当然我可以玩得了电脑游戏
为什么你住不了这儿
可是我的太太爱得了
这个飞机快不了
ba
你把我作为孩子
zhao 着
你看得着那间餐厅吗 (can you see the restaurant) possibility
你看不着那间餐厅吗 ( can you NOT see the restaurant) impossibility
你到得着吗 (can you get there?) possibility
你到不着吗 (can you not get there ) impossibility

** To sort
祝你身体健康 stay healthy
身体 shenti3 body
健康 jian4kang healthy(adj)
经由飞机 jng1you2 gei1ji1 via plane
经由 jing1you2 via (linking words)
打打牌 da3da3 pai2 playing cards
下下棋 qia4qia4 qi2 play chess
你的车是破 your car is broken
破 po4 broken
翻报纸 fan1 bao4zhi3 flip newpaper
报纸 bao4zhi3 newspaper
新闻 xin1wen2 news
# pattern numbers
二三十岁 20 - 30 years old
四五工作经验岁 4-5 years of work experience
Q. do the numbers have to follow one another? e.g. 二五工作经验岁
制造打印机 zhi4ao4 da3yin4ji1 manufacturing printers
制造 zhi4zao manufacturing
打印机 da3yin4ji1
制造制品 zhi4zao4 zhi4pin3
产品/制品 chan3pin3/zhi3pin3 products
退休 tui4xiu1 retire
清楚 qing1chu3 (adj) clear
团体 tuan2ti3 group
灯 deng1 lamp
速度 su4du4 speed (noun)
快 kuai4 quick (adj/v)
申请 shen1qing3 apply
放弃 fang4qi4 give up
股票 gu3piao4 stock
咱们 za2nmen we
最明显 zui4ming2xian3 most obvious
假期 jia4qi1 holiday
薪水 xin1shui3
我想要休假
我被工作录取 wo3 bei4 gongzuo4 lu4qu3
录取 lu4qu3 admission
我被工作接受应聘  jieshou ying4pin3
应聘  ying4pin4 application
加拿大人的口音 canadian accent
口音 kou3yin1 accent
特百惠 te4bai3hui4 tupperware
特百惠组织者 te4bai3hui4 tupperware organizer
