
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: nix-k8s-homelab/charts/services/homepage/overlays/non-prod
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
    target:
      kind: Application
      name: homepage
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: nix-k8s-homelab/charts/services/nextcloud/overlays/non-prod
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
    target:
      kind: Application
      name: nextcloud
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: nix-k8s-homelab/charts/services/paperless/overlays/non-prod
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
    target:
      kind: Application
      name: paperless
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: nix-k8s-homelab/charts/services/gitea/overlays/non-prod
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
    target:
      kind: Application
      name: gitea
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: nix-k8s-homelab/charts/services/gitlab/overlays/non-prod
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
    target:
      kind: Application
      name: gitlab
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: nix-k8s-homelab/charts/services/transmission/overlays/non-prod
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
    target:
      kind: Application
      name: transmission
