apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: transmission
# resources:
#   - secrets

helmCharts:
  - name: qbittorrent
    version: 0.4.1
    repo: https://charts.gabe565.com
    valuesFile: values.yaml
    namespace: transmission
    releaseName: services
