apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: nix-k8s-homelab/charts/secrets/kubeseal/overlays/non-prod
    target:
      kind: Application
      name: kubeseal
  - patch: |-
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
    target:
      kind: Application
      name: .*
