apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptime-kuma-tls
spec:
  dnsNames:
    - uptime.vandersleyen.dev
  secretName: uptime-kuma-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
