apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uptimekuma

resources:
  - certificate.yaml

helmCharts:
  - name: uptime-kuma
    version: 2.20.0
    repo: https://dirsigler.github.io/uptime-kuma-helm
    valuesFile: values.yaml
    namespace: uptimekuma
    releaseName: monitoring
