apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
  - secrets
  # - certificate.yaml

helmCharts:
  - name: nextcloud
    version: 6.6.3
    repo: https://nextcloud.github.io/helm/
    valuesFile: values.yaml
    namespace: nextcloud
    releaseName: services
