kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nextcloud-smb
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-nextcloud-smb
  storageClassName: smb
