## Default values for kubeseal
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.
## Official nextcloud image version
## ref: https://hub.docker.com/r/library/nextcloud/tags/
##

## Allowing use of ingress controllers
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  enabled: true
  # className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: true
    nginx.ingress.kubernetes.io/force-ssl-redirect: true
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer-non-prod"
    # nginx.ingress.kubernetes.io/rewrite-target: /

  #  nginx.ingress.kubernetes.io/proxy-body-size: 4G
    kubernetes.io/tls-acme: "true"
  #  nginx.ingress.kubernetes.io/server-snippet: |-
  #    server_tokens off;
  #    proxy_hide_header X-Powered-By;

  #    rewrite ^/.well-known/webfinger /public.php?service=webfinger last;
  #    rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
  #    rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
  #    location = /.well-known/carddav {
  #      return 301 $scheme://$host/remote.php/dav;
  #    }
  #    location = /.well-known/caldav {
  #      return 301 $scheme://$host/remote.php/dav;
  #    }
  #    location = /robots.txt {
  #      allow all;
  #      log_not_found off;
  #      access_log off;
  #    }
  #    location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
  #      deny all;
  #    }
  #    location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
  #      deny all;
  #    }
  tls:
    - secretName: nextcloud-tls
      hosts:
        - nextcloud.vandersleyen.dev
  labels: {}
  path: /
  pathType: Prefix

nextcloud:
  host: nextcloud.vandersleyen.dev
  # username: admin
  # password: changeme
  ## Use an existing secret
  existingSecret:
    enabled: true
    secretName: nextcloud
    usernameKey: nextcloud-username
    passwordKey: nextcloud-password
    # tokenKey: nextcloud-token
    # smtpUsernameKey: smtp-username
    # smtpPasswordKey: smtp-password
