{
  imports = [
    ../../modules/languages/go.nix
    ../../modules/languages/js-ts.nix
    ../../modules/languages/python.nix
    ../../modules/languages/java.nix
    ../../modules/languages/bash.nix
    ../../modules/languages/docker.nix
    ../../modules/languages/json.nix
    ../../modules/languages/lua.nix
    ../../modules/languages/nix.nix
    ../../modules/languages/python.nix
    ../../modules/languages/toml.nix
    ../../modules/languages/terraform.nix
    ../../modules/languages/kubernetes.nix
    ../../modules/languages/yaml.nix
    ../../modules/languages/sql.nix
    ../../modules/languages/nim.nix
  ];
}
