apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-services
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: nix-k8s-homelab/argocd/apps/services/overlays/non-prod
    repoURL: git@github.com:Vanderscycle/dotFiles.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
