apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: professional-website
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: professional-web-frontend
    server: https://kubernetes.default.svc
  project: websites
  source:
    path: manifests/overlays/non-prod
    repoURL: git@github.com:Vanderscycle/Professional-website.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
