---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    linode_api_token: AgAVbnLvPNFhoSishL9MGjtRCE8Vd13BVFxAk45tF0AxVFe8bQiQtLqn+m5U54aATIfcbaRoXozo9b8XZJrpXr9v9+YZUhGM+JUoCfeaekrEDSs7ms4cAveTh8FHJLMqmWLDOKbuKV4KBZg7ZDbIv03HEo/L+ThQ+6cl0eGl9zXndgi0ZjzC0atFyD7x5oEh94L/tR5E0HaOOBMmG2T3OyaorgOsUejFeq5YXMd8TCb/d51KEcZfpXE+KwKQTGv/ruuhVpmQAfOvU9EOsphYEcCtx0/2MNh8tRTF05DYnKFSvbo+cqVFx3Nsi2R/oN8plvZ6VtR7j/6aTg61uGyXJF4Yz6oBrKvYVlUHQQWRirY5tsrUIBDkXLfbkmJyWQXyNHVXUg6cgLbsrioNSjyjvTVyMq0XTLeqp+255xDmUPs2jNzxy7DNzrznerPO0DNXUdXQlw7zCx6rW87ZUjyW4WtUR3nB9uEKaltXGFuoxu5pnfhI+zyncICcpJSz8ga9NAIIKBN/CjLGKwBATNW7bN5CjXs0KFddYfxqOOBU90k0HCQuvmTumjQvEL4JqQdNVs6i1nRX4rJbFx2dox4Q6kaMX2mq2PC+9nIHoz1Xl90gXkvLpEjmQqoeAMp1IfUOa+8NW7NTN2UaDuBUJFRrKwGEMzxIbbx06bt7K9OmQr3hBkdCMzmls6uIWntymtHBDrIzGfKBHMrN0ZUb4Ejef6wnYV08CF37A/Tz78+capzTIHcwjkMNM13uvtQLkdTYoQ2/2uZmy65Tq1P51yY1ROcaVw==
    pihole_password: AgAh97lkQmhabTY19dPu6T10PlrcElNQkNaohVWNNld34PjBHD/RyfKZtOuZz1aVngoTiYsERbMVaKum8B7EoyAZIq/LWdif3f0IDvt/oe8Jw9sAb8/aqiBwH/1juGkx0GAv73bRsYR4vpts+ykx0uNIberHrasqNwKn8suyX+Dw9A+fyLCSaunWn3yH5Nztuq25TbROhGvnqxwksB02gGyaBae06LY2hgv3VoogrurkSBYrxNuZU5beUrhrY1pirstInHBGKjU4ZprFaEHLRacjEO6Fuvdd1k8vNkIITZBa6nvXY7yP1dq35hhx7pXAqESLcocu6SCMbBHk8l2vkkdjRFPRQKpsTm8HKPCV+YHQ0Qw/pFoHVqYGfKkwMs04OYyNvomdYQlwdMCdhtffm2jC3MYMBiGpo0B9jAZO0mkQeGWd6oJYD9tqGwKt7014YpYtYXa51mgTvxitPcHSA67IyOM4wVyuSsxdTKvl7kpFbjD7Yn1fobkg33KmYYguAFpudaseO/kYKr5nLPXxe4ZgeEtBeLdwsOU3Nis6T1wVajqRdmVI7M08B9lI5zF6GFYgNiMFjG/6uOefH4u+RlHvDzWY+YbPoGU7CDWBjeWPGRI/Ix3/lIMHnbbd2vLQMuVttgbRFUH/Es/IwgRr0sNuC/o25xn1KN+5aGWqS8nqhTWkIjJrEAfCtZFR7G8qBeYwBFJ1/lQ2Ek4FqA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: external-dns
      namespace: external-dns
