---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    pihole_password: AgBjzv88Hu1t4O9TZg4oprCMFl6CfDtqIAyJPuJ+NtArlcsy/xwPF7OrS/j9rFTsMAOh5VeEE2cplJBB8sYW0chlyhyCQBUdQgh8m+iwMA24r42ThNZMPHi9G4WMzinEgP/BtrhUGgXgQauS1yrAs5oXZZzDKQFwis1u/Hi4T/C8FCK3Qm2oktBIgGyNYCSX1kg8UXB2HhwvkJi3ukwPBa8cfoS86nw8jC0D562LacxioyvsdhbCfZ8VR4fC3D5EY1vW7QEjzQGXImLtNLbjlGlvAhOkcjPbI9ChsIHiqzGliElpvXVflXas7yYh3dIo58xptOeZGdsgyem22midxJys5xAHbokGvdfX2XHXTNyOyzilOkAwRLoAgX37hryMWeJElelXTavV8pfPZWWCm2STOStngGXDSx5fqQkuyUNqeCUPey7ty63s2qNQrctm7rKZb6d+OrwEzKiK4q0N+qKd4KOWJPnIQfW2CKiwgLISSkmwWrb0Gg/9v6e9V5xAqkK4RlqFuos3fwJ9Wdu5r+CtcatY5tsluQUamc8KLt4Uh+5uNbBAHebe8xHCluQu9Jri6mbxhywg2wm8m2tHMic9jyP2r6vqua4t24ZMKQeQRU3OJB+1OR+xNS/8jJO575ONvlbn4Y5HxRqr7Q1HjrQ2KQMAfYOzikyZ4WGs6kiCdl+T2W1Jine0AEgg92PtivyilVEEiOT2g4oJIA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: external-dns
      namespace: external-dns
