---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    linode_api_token: AgCmM1iPsoK1kg+wp33+Q/7fy3DE+NAfHgeTgaAdjC7LWEi2bLn6H+o7PuNAYMYGkK6XtsEOHHV+q1I0sZ2vW1HtKkuqht8yTNxYnEqlDpvGTrFgZRTO+iHnyjdSbKEYlwewAUN81FogmmEQLo3NCZqq5ruTUj1A8vtxVxFLipzHNPD7V3VeNuuNE0JsECh+eeG0wGRXnPxzxkq8mooPUJRlF176+Zusdo18sXvijMq45otXpWYomX377yI9KGAOLueHHVI/LJYUb8nDGBkifHUQOO05kUgzRqWZBEBjudNDPXr5swE1cosQyyxKCh2Iy/ofMX4GHwzuXZe8TqaVAQq3FbGB0srDIDQR/Y7MjWR6biZTx8KOK3EfCyns3Mb8ZWKhHjUn/TAZCExJYGja3vKz+R1sIlwbRDlwlaTtjVUnXekz9GI2eXeMgjbYGbWD0Ht/zb+C9IJF5NkRlVCQfvOtCVsan+vzNA+fvDG0sxCtFNeqC8+FgMOldhotu1ZY6nPEyygUw/Q6iLoLepaCO4aEbabm/WMFLhdYs7Msmjq6OpQILrnlAOmLNtfY6mzfIGOHYIvc71aplkuy722qsrCTyiG6OmjXbYdbAzRsjigKTNZ7ZGYDmo3uYVJfQGTzKEvtcbiga1dWfufLz3qS0YsAthrhdc/i57Q1ozbNYb9XQ6J4BP2AdttI/EJ1Z8RuoYVuUkDdoZeoJhtmBWcF20I/ep+BSxiuskbtan78m+Is7PhFWFV1KX7gUw2o0wNfL9BJvfTSGUM9M7+WG7r7xRjLqA==
    pihole_password: AgBsAmDAwBiZGYqjtTSRJtJhKwrVp05It9hkwyUQ2kDGQ1w4h2XD7gohAw/u9qY5fOGLFRDozCyWImGH2GPDjs3Q7EVXIkivP38zTqSGrPa4W+G7tTTh8kEE0C9tKLZyX8eLVUH8PA9kC0yayAkMhOwsT+3XWOt3Tibe0bZOiUbKlVTPvZ2iaD8ifPCn/goP7k2qWJl1xLnC6I5PswQkrE8QyyRoi9rMQo7lqx7rH/HrWJpPbX92gJoKD8u1bYGb1en6lt2OeLrCxfpTlRxxULum/gJjEM4ioIJbTzV6yCMAH04FIdrUa0OvXG9MMhL1uJsxwtv2mkBNad4Iv6HG7FwFjluKgx9hV3Gu4CnKxRsP2I3OzPFnvu51Q/Efroh22+rfRoN4kOGVJMy8tPfDCHYYMV7tUARMlvreJQqe7NFZwYXy+afBTU0FZEp2ajm7ZgZ1eTzS/zHLlFNjwh1mJw+Fbn/4pOQYLrXpEld91676RSMqKrY6U1SDJ6qRwN8z24Ju4b3WAeihxypOzIag0HznS6td0C2pyza4n4emFRC7o1uFnqDa2I8dpo1DtBuZrG0tXShjVqqyIMSvRq0QCfuyp6KTJ0VbrQcJoxFRcOydz8Xu82xyUjFTZ+j2wxY0Xa03Xp7iPoRo0wZ+16XF9cCKPRthhLM8lMOnOOZ2YdbM6qtFnfuu8a16A8XIF5M5rwh/bE9bfvsKMjGznA==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: external-dns
