---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: external-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    linode_api_token: AgAvIpHtQ3Ij/NdUfNEpwPKCRRVK6sItHtUh9Uhv5MqQXPIgmKgdkajsEnOlSG9aiMa4zuN9nEWodMdVvzFaLp2DpZB/D9JvbqfQHVAZq58HNGD9GIdhfzsVQJFkwc2lvpcke2agiWJZNXZrXuAAjymEMdcxpVVyyuv0JHt3kqd202AL0KEk0JhVofmDvJQMfid46JvU7x/k2lRNSDJEO4zJzKgnPUqWACYVWW7qii2iWuGNwHVB2QVRnL3kCH9BDKYjsjNngHtBhAY2qf8S7WrKE8YFRLwZdA0kdR7VKYK1/qMvGOR+GrtVVHzw/clzdr4HlXxRNnyd8oYyMH6dGDvMzOucroLY8INgfRfSbMLviDttgh9jarz+XKGoXHn1TQLGrQCSzY3t9lwlcNebAqCGoEPBK0WnA3nSpm4y8T0kxUrJ4Lk2WNj5mlcJb2kRggN+hscnxO4I1vXs56FeaU++lQZovjxntdpEoxKM9uMaqvNpIA/q1x7vR0svj81vau5P6Q9iJxDsdKtDFYOeDaAgA6OA45Y/6Y4b6YJpYb53HpjkCnbFGXlBhFmmfFovzEW5kPeJKQiSEmKMrB+k9t9zc6dPN1rwLrRcs67GNsyPsovFDeRlDGsd48cAOHKrngyb+WYUDOzC8apyjLNTxcdFnYLarryJWq0/owTLLyCPGoRCWUS6zc/FmmGuuGzU/rLlw7unMPRT18l9r5pXdjmzetOKefomdNpBe9+paHiTkjPXUd85PvEivKj/0C8eN827/dK7t/45VEheQJfFsUte+A==
    pihole_password: AgAj9+m/fn7N5FULmqpCnPs9GnosL/ftXuo04RxDTjjFs57hv86lJILqaH/gfKQaLJ3YmzomsHsb/0F1ZTHmEwkVzxNHrXhdm02DhJPsVGD4f446goUAZ5e/JpiLm/5MbbsNjo0RY2MCWJrLwBlSzFfdJ7q9EKlBWqqjreFxzfxTcYumW4ybw7IiI6U1gWm3omXG5abNXWo2Luu/JCGoXfY9TwOle8eawPWorfs1PwbKBDeKWCkynJocH6VURtzbSxY1galsSiPLW8MMd4LHupxKFouUd2QWjmk5yeLoZX8fowjv728VNteKgJa4jNjTKn68qhMgPhNRVfNOOP4s+NytrIKuqD5d3QmgI0DNlx0HPqdo0AONPaDk1xo6pQvKzBOAmJ3BEpMn+0C+v2zekX/eUykOe8Qv06avgUxJPkIw6Lob5r4+Ek9e40SLIadz3q/Nb1CwxKrD9ZM/Qg46BUasvuKHuZzEsScL8FL1kK69ZaSVygi5AJp+ztYNuUFNcXZaQ8MZ5U6si44ubRCWKR0TpKk+CeixHiCnQwMfpFEQuLkdsf6BGDP3JiaoU1BhhhxsN5eNnOygBB20WepqIfnVkZKtF4qkBWNlp5iZVOUjHiZX/SdP2TJlSKQ4v6fwI4rjlEJORj0qq1Wh7lntxTxApAmKbjv1YYwni5eZq8ONcbXl/KKREonXb9JW6MZP4cy9H9W12Jeivz9HQg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: external-dns-secret
      namespace: external-dns
