---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    pihole_password: AgAVY8a2N7xsd85Btfp5KvnKRhUXsx6MOwfPm3Mpf67x5UtDWX5WxVt4WBCubPJHrJk8qy9KBVh5Spj5uELapqLQsxp3xBXcQB080XN4lRTfO4RrnTGeO83z3Hbg/DUmFOIqgEqIkCm8tejI3BK60bdJH4Pfgc8t1BDrgccEsXoZB9/Rk6jMtCIPW18+v2ewAhv3zE+NkW2ZgKDof05hUplRoMSXw2dd2gIWfOnCYkicUX2mE4lOXDzuGons22hGHbWBXPGv5tdHyU3GOkpl50rxqNkca7bHZCVhmcFkg8+sHfOFUF7QZHoZWrca2xnV6isuTtxhCACTTBVKqDTCkwXE3SoBSCBOahieLuWWu9UyWqSncTY66YNfhEwzq8lNPZZGOIOk19vXWzYJ37PQIG/LkSIbqMpnfKjSOjOsMApFSP+XjCegw4QjIk9dF7PF2o10BnHA5BfAZipcynwgKUNTtiRNonrDfvBEWh9E67yJiLy6WSym4n02kY2+gaTeutT7bZOdC9t+dtIulE8V1QnZaopbxpzz1IExIsy6q7ofrQhe1MmatjW59G+AW46T5DXY6GksikstuEW36IzLRecNsxzTA7tbTxEdaidwopyR64Xip7tzjI/GGvjO7LNuC/RPMuPTdvglGjOEocTKEOG+RqXuHtGNov1VipMwJVou09mle36OIVVw2bdYILCTRGmBQNNhVy6WfitMjw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: external-dns
      namespace: external-dns
