---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: externaldns
spec:
  encryptedData:
    linode_api_token: AgAC1U0EVCDxh+Bilk1aCqnQYEEv9ddhVS0u4g9ErWTGJohdYPLevOF5lrwko05FdDv3JHg6QlFsq6kBudKFAPboBOIre2ZsLzSZxgkHXQTnUdLM7q6Sfh6KAZZN1xWIOQO9+Kpd+akbKm/T9gOxJOvnDJOCiYhL/SiMBh+Vz5WSAOahMGusrLGU/GraaKtWvpmI5ZHpIBjRAyj6cZLBhGe/U6ke+ouu6v1cCCMgyezGrGmC3md89JeV97LLvcXj0XUAnvJgX5gcwxn6wO6aRyZTN/NThrHjLqcB++zoGuYJ54mZn5vRpE4xmFV/kcgcQGF30C10l0EallcWo3bUg8gsk9NVuCftstm9zIF627fxwoFfTflKHu+zwwnZI/VduTXIK6uBsh1lPdfA0C09MawcELBhvG0RuhHt4HPA221Al8Xcmi+eJ3T+iAHrFn7olnT8wO9wtcQ/HTC/r/aaA5A95i6qaMoIlhkl0nvpPWeqxFcUcUnRfMn52p26H+WiKJt9N2vLZBuCvnyzO3vm3ca/ZvySOJh8BIHyMVDw+ueAj/5YyBmy1ZFr5CQfW13HPA2Z13lomcZ08QevC87XNhHlnTI/3mGWipUDOZU9ZxFSJiTiWXn8ecUT79b2JO/zdhv96xSpnTTkpcuSoMQo60Y5TRgTfniz0kxNS1GT9Y/mArPSZ9uhbRKB/gZ0gExsrBXKWhLRDthmS53QCdoJpFki6mGB6PFzS1OXAcz8CJ8UCLXTr/z1r9V6Rkj/bWRKRD15pooIRDy0Do5vnFM7ZKsP1Q==
    pihole_password: AgBFERDbVQLvpfAOvKjI9yKh+Fc8YqRZVMQqoN9i9jwLwLpYkQeZWpE8kv2DVgD7krwD2uBwSeBmlIVsqiQqkwdRxZpr/vmGTSrHFvETB+kZbnH2ZFGpJGi1MJnt0aw/w4njV/mGFk0K8fHQaUL00atuSGQbsj+gCxI6i+W27U+7PzosUkA4BWQmjoHK/s6dxWKuL4rCsaOz5BNeU+MhAhD+thD1NvJIV9zFwjltFYQouPoBvIxKWsOqdHGkHng4yna+3en6QviEH3ykJxHDmc627XQ2OYl90T3lAut9kremKIOj4emtUPopFQ4Yb6QIBvztRZ3LmRtPs81Rmvs7B9TaiRvG6/5Th/NYiBxDiHx8uIdvnTcwCrFxVUpRtSc4gSZoJl7+6DlRq19Zb8wsMo73LF05Q7iUIb3UdvzNUl6myZfSNQbSyzGv+Pr+mHiLu1LB7XLFP6MGRCRBWVE4hOjcot46v4DGUhFzCc6pXm9o0iF5rWd6dNthikfk3IezB97/5DQ+3j/YN5dmc3UdIhI0h+Xg+DI7yla8SumaZMjSIxbtsALXt3280b9vs6myQoH5fkEoaE1/vilh9rdLFkGw26U46R3HF4if0czPjGN99o5xPgoHLJMdsET5Fx34bFOyyp2FaPCSKlsAfxnaV8MwU1F3hBJn9JwnvbPsZTPDJFTcYIQ9jlC0owLiu/r02IVe2rwuZYM10MPH3w==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: externaldns
