---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    pihole_password: AgDPn8tNw9Gs5h2kvQqNgUKdBGkDzvpbMlHGhfETwRQRKdukkk+DN5xMtGc0NmsTr/zxgjL7gdyJ6iby5fUHS38kbMim7S3/KAgbyHqwWnEM3GlOn3Uyi4mFZeauEo0g4/ObpXS50ndx8Vb2NZmv8yNYDn3kNJlowLvNqG0TnICdMVh5rBB5nqROWPF+q3EX48OQNZA9wytlnRgkicLPzWvTj4Q3ypoXjO+asFON+08s3KiUiKxE+NWOkdbtgFLPjN0Zx7RkKlEaCsQ+ZYp+ZWgJK7zc3bU/RjzyWt5Atw0EJz3tOs9P+X5fnoltOvCAYDXf/jIhDyEdqeebd10JkkdR/TyfZfSMQXiWdsppWi67bEyofYN6L2DoZ3U5SGdSuihjd77lhO30E8D2wCPB1uL3Uyof4Wffoodi8KgH2IWql8yvvI35wOe33jUjTd0+PdxHG1xkiW0CRDqiX8qWQ+3B7mwMXMWvV35sYYLaBsqxXYsTh4G9RtYRZBDjZZLu4lXpev7ZDyWspNFFjDt/c9I7Qz91IRg6w+dlKJUgiHiIr2EqGgnUHiKBS1D9F3X9a7HZPnw1JNwBw0IoWKGMoWpTta65The+Uxti2V5iGeHzoKu2eQlM8qYOJ5T8B/ApQEnDValbsyRsASSDfSZbicE7/+18WXRWOJ+IwIxKkhWSSGUwueHHV+bLi7v6pI2//jFqF7FAZpHpezx36g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: external-dns
      namespace: external-dns
