apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://artifacthub.io/packages/helm/gabe565/paperless-ngx
namespace: paperless

helmCharts:
  - name: paperless-ngx
    version: 0.24.1
    repo: oci://ghcr.io/gabe565/charts/paperless-ngx
    valuesFile: values.yaml
    namespace: paperless
    releaseName: services
