apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://artifacthub.io/packages/helm/gabe565/paperless-ngx
namespace: paperless
# resources:
  # - secrets

helmCharts:
  - name: paperless-ngx
    version: 0.22.0
    repo: https://charts.gabe565.com
    valuesFile: values.yaml
    namespace: paperless
    releaseName: services
