## Default values for paperless
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.
service:
  # -- Configures service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    ports:
      http:
        port: 8000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 64m
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    # tls:
    #   - secretName: chart-example.local
    #     hosts:
    #       - chart-example.local
persistence:
  # -- Configure data volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  data:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/data
    storageClass: "local-path"
    accessMode: ReadWriteOnce
    size: 2Gi
  # -- Configure media volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  media:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/media
    storageClass: "local-path"
    accessMode: ReadWriteOnce
    size: 4Gi
  # -- Configure export volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  export:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/export
    storageClass: "local-path"
    accessMode: ReadWriteOnce
    size: 1Gi
  # -- Configure consume volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  consume:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/consume
    storageClass: "local-path"
    accessMode: ReadWriteOnce
    size: 4Gi
