---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: factorio-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: factoriotools/factorio:stable
          ports:
            - containerPort: 34197
          env:
            - name: LOAD_LATEST_SAVE
              valueFrom:
                secretKeyRef:
                  name: factorio-secret
                  key: factorio-server-load-latest-save
            - name: UPDATE_MODS_ON_START
              valueFrom:
                secretKeyRef:
                  name: factorio-secret
                  key: factorio-server-update-mods
