apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
  - certificate.yaml
#   - secrets

helmCharts:
  - name: ingress-nginx
    version: 4.12.0
    repo: https://kubernetes.github.io/ingress-nginx
    valuesFile: values.yaml
    namespace: ingress-nginx
    releaseName: support
