
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loki

# resources:

helmCharts:
- name: loki
  version: 6.25.0
  repo: https://grafana.github.io/helm-charts
  valuesFile: values.yaml
  namespace: loki
  releaseName: monitoring
