---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: factorio-vanilla
spec:
  encryptedData:
    token: AgB+pFdnCX9mQ5HypRrOm5owiyUHaiidBdLnxyFzFo+zEHYwHKvJ8HNvBdlcxtLUr/+A+Lx34TGa0ohOHqV2zdqQf4F/29crmijd3spznE7fDJQ/r70DJAN0Q6tW15UD4cQPUbZcph+sUm4Y+CSxgl4FC2aza5oqDkW8Klwy8kIWcZuTpID2J0xg/m3URUaXQMi78TWLieVnJyVXWz2I8Joj30zJqgK9QUIsVoUgUTdQyAWhEK4jvjU9ZisnZQ8Tz4fO013B/clOmNPeGsVSGazVngtGX6THe/DzVUhUgSoRwVCypVzwfO5RQ9yzVrkgx+TpGVwR+LwwhEHOSsNa6joaAu2//b+jWe7Yyx/clRR+2owpcLzG6JLj2OieJvJqemswifTQy+u8jBupfw/Mpnr0KoYO3VcvO1sYPy5U0UoRrNuF6R+Ds9pJNSL6xDTDsKX1siB8NZwuCf3m456Mx90TQfWApOBt7bHN557WGPWlShGKp4VT8x7z4b4cSHmdRx1VNLMgSExvvSoKQ2282MUX1XJ2vSqssmBHWECyfAN1ZGHzLykazAABpeY3idVCMoR3PZhRPtbQeNhA30nyew3H2k4zls7ryiFRULOA897gWiI2QjhJsYzxygveSgxL6VQgWJH2fyGhNERjKY7uFiUprNY9PsHo7UrDi5cShwJdEiVYONqPNvlemA4neP3qKosZXHc5+fQTIzxfZzEAAsxFnHMqYmnC7ighAxq6u6MV
    username: AgAGMxNQWFcfAwbuNPRNZ2jX4r9fmJRlpioTL59y+jBVK0revdHwO62FI9NlnGK9ZQlMSf8pM7C0j9+yG0BjrW052Gw2hFwPxbnNdsCyq7jN6zt/mjJr5TXZpWh0imQjFZSl8Pr5Vfkc55nJqvQI4d23TtjlkGMzEv3BRrGwOH1tPC4JunLzcvWlKf6kvxL13bsWgIeS9ANwSbDDOS3H9+5n6cuJKyh841BwSJCY8AMm/rOLFyZ+J+xbjFZV1ggJ+VnGY5G4vPgYVohJWB2TEvm7fWJGu5w7wAPovgDt9bs+1ZCm2Gm1skPiSiPN6dce2EIdO7iAjCgqULd1fFZ3LASi8N1DCNRRqV1+u4HGvu8kQxNbv1w61tNDOCy1l7k9amQ8W1wNTr0CVdHJarDkig86aItxv6Eis56Ln8IvMT905woet6w3wBqwWXbs/gLhRdQ7GVLBQp5vyMfNBEi7DCef3fU9kuCiQlFdtxnb7inEFzZ3s2eLDT9zbqB/NurLkfJJXelmDZDd58AedFzXxVSvkjvDLZniDGuVDjSZtN1An3DjIpuwjdaP7Zz1qdXhRIYCxbaL1sVJ9KY2dcA7nLN2CuKBdll42GycR9b3QkV5ZKrXmRsn2ZV+F8/RfMzfWIKLulOs74qOrkDL2Dv4p8wy84w3KuLBHPOBOEag7IWXSaau49001d0fxdiBiDCH+YVTXDytkiAB7CykLes=
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: factorio-vanilla
