apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: support-cert-manager-controller-ingress-shim
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - create
      - update
      - delete
