apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# patches:
# - path: ../patches/patch-leases-permission.yaml
# - path: ../patches/patch-leases-permission-cain.yaml
