apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: homeassistant
    server: https://kubernetes.default.svc
  project: services
  source:
    path: charts/secrets/homeassistant/overlays/non-prod
    repoURL: git@github.com:vancycles-industries/infrastructure.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
