apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: n8n
    server: https://kubernetes.default.svc
  project: services
  source:
    chart: n8n
    repoURL: 8gears.container-registry.com/library  # note: the oci:// syntax is not included.
    targetRevision: 0.25.2
    helm:
      values: |
        service:
          type: LoadBalancer
        ingress:
          enabled: false
          annotations:
            # nginx.ingress.kubernetes.io/ssl-passthrough: true
            nginx.ingress.kubernetes.io/force-ssl-redirect: true
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer-non-prod"
          hosts:
            - n8n.vandersleyen.dev
          tls: []
          # tls:
          #   - secretName: n8n-tls
          #  - secretName: chart-example-tls

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
