apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: transmission
    server: https://kubernetes.default.svc
  project: services
  source:
    path: charts/services/transmission/overlays/non-prod
    repoURL: git@github.com:vancycles-industries/infrastructure.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
