---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: externaldns
spec:
  encryptedData:
    linode_api_token: AgAw5cN67IG8uy1SFAi+q9gUSIXA2eYuzkDo/NWwc58lgf7wxTK1hQF1QmgztuDUVM9Ols1aQrOv1HL+o3izr0io5IMPQ/LXCd3B1dk12XVCe3AyD0bl2Jn3wzuH9o+n8JE4nHfPD5A+UkhEi9U6yBiwjsDJe6g9eZ8pkXzivWNRK3+Y+TkOp+Kv9+Q92wxOmWVHN9rnwlbeX/OVauiURG5noVwTkSM6Q8tD/dHhF98pwRllJ/4DnxFJ1z6drhAg+LZkk8hJwA/bk76ewMtU0+rcZGNaixSmbdy9y4FCkx4LWcZv6IULqHVsCLd+lDU4iJBLlv+fScsx8bcy2B/6Htb3bVdEyn8yvQxNJ2M4xuIgVOAyjzvNv61stZTCMadC7VJUPsw4ff2QE/YPoQCZIy3djCEOQGaY6oBB7YFm8XM17DVZHHNBX4kVMGBmGCkv5cii2N1NwZfWooqT6llwTdngEJGT7CLT00j+/cIbhIK8krYAFIui8o6jtxtpRWUnQ0ehKzJ+EiQ3jMWwErqgOFY6/RxOqdHRLsW5ObTAZZS9o+hPTxzGUQym6/8KmqDR8No5HAR/gWlb4JKV1nVwfW1WEgF0A00dgpB4tIYTCvRHSZER7hGSKzQU12L3JpHPhsSAes4BX/J2dvM6nLh96Y2ElniRI+4SehpqgugGf4wtYSrN6Zu2Gcfi0CYZ8WUH0VyWo6kuI7qsUvrv/T85FnIjw4bCzRhcEgbbpZHJZSCU7crHXCKjnhpgnNNqKth3foPf3V08VsSA6QVO998Prj0/Bw==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: externaldns
