---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: support-external-dns
  namespace: external-dns
spec:
  encryptedData:
    unifi_api_key: AgCJ121I/nEghDOj732hHvuhk6KGZ2qgqa1X4b/a59FWnM3GZ+YQywfH6JXSDW4CG3GaU5h5TBE2rEHvbGTXAaWIhi+XSXlGEiPG9rwt0QfjzETZRSBdRC0B22rSeB3gkkaMLVEQl/yQFL+F3YUmjpjYX27ZG6nzEKLj6EoqlLru4cGgsuiF0A8G33l4Mqu3I2u/rFEFyGyJ4oL9tm2SgHXhJjtg+78wzB7wePM/9yLSB7giA21nm5ZIuBJIE1R9N9HoeUcwhZaaHzT3sJE5uvd80YXx8OiwcUKKBwpv1Qr7e6krtIWPc8Jo4BuRhxoGj7wurTS6WhqgoPMqlK4YFVzuG08ktzbfJYq9NZ7/lKuPr/krYKZNPI58Pz9YfKkk35ofkZYqqw1qmN8x7ORR3E+0WPNI5TGnlKtiu16GNIPJY71mphe6dqRjg/JqAIR4dhbLuoeal4PerT3y3cWt2HEP18JQhsyDTICnFDbVd73VeH4z2B1+ZxU8plO2qpbkWRUG/C8ZODdgxe5LJUoeBk4YMRZK5Z2BVDHfuu+17o5zLvSfBLq0ypJ3TvdZzdlXWKK1V+0KE0bMHtAYrBUnc3LJsdFisV5x36uDOPlHqMpUtfqRQY+bM4f1UPd3L0CoxBLfcKfjdCwo7ey98E6cbr88Mb16TQkzuWO3LWRI57X6kkm+PhAKHVeeOLpMP97Pm6VrYYD5GEMYVSVj9pS7+P2aXDxbDWZH/R09h5017vcWyy4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: support-external-dns
      namespace: external-dns
