---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: support-external-dns
  namespace: external-dns
spec:
  encryptedData:
    unifi_api_key: AgAdLLF7TwGd0GroC54Xtnjoz6cQ1t2WkOAuXKDLHSJqaFe/hdhSHHqQlTysX9mKQB79Jpqzl+U6jFp+FUn83EQ+Vu5Dt0akE1ArR33MQbd8RP0gneBqe2AxSIPA8ILzPnTkjLzsr4iFZ3ZKQlebAfI9zwItJ8L4VWJyz22aBLwf3Yg9guH0zH+daLZ9WXUufmttppuDScN7gRwPnfIQSFW5CF4Qigbp4mQabLceAbq02yvdxMRQm702MRbsiKycbHlBwjDpuki7L2oAOiBXsWsbAQ+TCN03yPPkhYoX/LdYIDVrN3PvC8nXDOat/R2th2nDXeOeT2AnZN6F4sfeLAaRsXTcXXNkki4SdkPhd7cLp9Jretf/ittGLejbIs6o3nybRmUxx/e55d3Tw+DM477OnbAd4Ab+6Bc3/BuaeygZBRaqcpkB0+V11lTWRcXnUgwku/nYDi56VCZXkJ3NGZw4FbmdnFwvXVpc8cqjDIaF/Nimec/FlG+fcqayla/kFpaH5IsDNMYm6T+WRRX15h3nPuSRa6KFjwIaormdTorxCH4dWjvrmBSkoLRGDObvRNa+QvtKIr0MRD+a7yBd2RiMyu015tjO0ZQB2iTbAmM+GNx1vQKEcq9zN3gytLLH9HReHGtnNp16J8Fu0bT4GMLofmWxyUtMOCP/bP12MdHELIfwRcZFrZQpLtb9COB5N8eBNcxGycZdwrzF0tz9ljIEjK1ZeTE3vCzlYb+UGMiHpSewR+voA4TqedWHCw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: support-external-dns
      namespace: external-dns
