---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: support-external-dns
  namespace: external-dns
spec:
  encryptedData:
    pihole_password: AgCf2ShvK0FppOQFCMrdcCGeTRHEmJ7Q1ETcp90mrHHG2gdPE+t25tnkG7uRldHcq5ddu5QX5U1szJt+NXbl+IaFma+QQQpDYUCrRx7n9s1JeipsXjdSDjQ+2PE/LFLSXbzipVMqbKNw9ljodULny8jS2TOO6XJ0f/Yv512Vddc5d8lcF4QC1e8wfB32ey1Ke0WCFs1kTOhib0bpMGMuGIGstWsyflRA/9clahltlSgVZq/61X9XWDWSlWpUT/FCbh1WvPSIAAU3KZQGQabxQYfh5goLeahSm7kKZ1kV9AXLmvhGrMfW1FzWqvoaeSeuhiy0bUu0W2/TUVSz2X4WCOHWjRBTkg6Y8BA4t81+C+2qILNj10kKS2he//uT+E4V1AsN0LyoF9U0ar13mwLsuWLY6vKTYFlg9mUpqCKPAsggeMPQg4DpssUKCP78Jpx9jZ8wcMUyAjXVmo5QjJX4hBPZVnQC1++gSkaQQu5xduxViW1UVJmIIov+i54H5PVS+tB4q/0+qLc4jrSrLRBkQUCUyZEOGRkKq57L4jYkzTnd/xsakLEbGgp55MlDOZi7AZ14PmZOjJob/VdfNP6J+cfB5lZIjz1fIZnX8NQFIlZTUekthpc/zS9OHeyBrgHmHVzGOHRzpcNnyXAVw88UYfEQwIWFK0kPp8CkT2Te/PVjHsdwvdhEKqrPiK+lPTFx4FV7pS8wvj2htDjTuQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: support-external-dns
      namespace: external-dns
