---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    pihole_password: AgCT1XlETfUC/B3bKbW7Ejcs3nlhz0Cu3szDtCCHE91sYpUVfD0klrtt4QSQQOEXaKBOOVvdpMZdR5sNUPN5sDu8dsUu8Tngpe3AygqIrTjKG7SXRJ1YtJCAEuada2f1LnKNc8qldPi7m+LFdBpGOb3nZeiOQFbZFyeU5xNGYMc63BBBwckO4WuKhjgC0Lypzwp1gqCc+zEaOdo8KmtgfFZmsGmYB8idx6lXfMBzBohfJZwqbSZT9F1+AdOOhqmIP1wA3Ex213ZznZWQu9Qe4BDq86HCe28MAIN9h7SZMxVnLciHlycFQKRCbbE+GshEjDcLa55rOuT2vrK/aMOfJMmCKm36fDQaMWKSP1Tyk+ZJmmUXs89+FBjbl14zYgie1lkKqULNiL47qKl6rGHuExyvwnyt93C/YYq/BGIPcQrtPEzSRm+HruOwdvsZQH3hxJwy8SufHIuy8aUHpwMQoUNIFt0IYcoMiZX02Er6gmaFjlk0DN39wSywxS9ytwiCICaa6K/P98xr4V/laeUbjvb/xzmlWORZ90aD7ngcXibMGeBvQY7gSmNKciIlOiI82D0/r8JALMpll3WpIoSaVxZ4Y0pDnvlQrLUBPtqDsuvDcjVi/XWNz4STRBgwfBQdDOYE1xR56LgijcdUZ+X64mQmCRFfe2JTzcI7fBkpRu1txSBKJzRbKgxRP5+UT/4URHei2O6KM8H8erxJlA==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: external-dns
