---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: support-external-dns
  namespace: external-dns
spec:
  encryptedData:
    pihole_password: AgBp1mla3olI+1awccF3Wo1hqVObt5B1EF5deM0qEzjY3eHI0e2IeagwEUbflx/bmqv8fEPlWtl0gbU7zLByprs/gIYRiYnav5upxONRXkNToOa3rxeSEqygMf5a+i6LLmRCftL5ys8co3VhhnMjCCkRD2ULjOcED67zXLzCZPe4S+7faLpuajpGfxn4M3IK/D0luGwfw/MnaIHaFQIEHSvG/iWMcovPp7PVsRyNqzdJtBWSp8rRpN0DOo2ZMB7kUy50N69tgZqHOT+iD6WWQSB7dDiL8LQUEfLnvMlCsFvanc5BHAA66yZP/zT/fXM6IOSwJojAw08rldBa/6DhYhkM6WmyJtZ4dlgscVHuooZS/hsJEsAtzNU4fij3YkbT6OalUCaaNcTpFeeCDMkNnQHXS/edQdYN3y5svJ1PRrGf0FeP+0yFjxY4M5+o57q4+EzL6Az5jzh7lkF60VSKl/dLoH/jMjZuhiDFHge9PYbYmbTr+8r73bEhxWfLTZGdpVgqOLETMF7dzjuFcKzUrvTsHIGEKPrupO4vy/EhFHKqhaMy05htAz/gPy+2TEWJ1XzD0JINLJetk8r8XxKIaH6EKbPGyXFIyp4IcfOe7s4Ea9c6TnsBmRC2vX7fwJVRfdJznAJ2zQHlwuTdTssyQ219uQ5Lt2k6rOyhe1Z9OnbB5Y50IkWFAICLBdysYZgRQ1tWduD+hqg5qRJCZyDYZlUH/g2XoLFK9DtJ5b6I2VSIEw1SjXnCdHG/ajh1bK/jYjUI8THHDAjZY6gLAESQX8aP0A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: support-external-dns
      namespace: external-dns
