---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: support-external-dns
  namespace: external-dns
spec:
  encryptedData:
    pihole_password: AgA910ZPdtXzGfdRApWyf1M+HDzO6YEgUFAIxH971HA8bdK1yCaA6sB7ghAXJxSZdre6xvFbbjkcIdr0WT6Jmu/1kC0pxBc7vCrfks1qizoP6KGLll31NDsGklF2hUGbBHbE27+KTnSriFL0xqFOk5wNz7Tt0M5lTtXnuvOwoWwsmTYL3zkeouLd0QCebV6W+UlVp0LNoYUknZpBlFtgJHU9fLBt/9Fbrod+YDGO5jlk4+XlHJ5sQ6F1UfOtmBiV+R1LzooZ8wPHViXqI5Di64vdEdlgXreXhwfGFZL1xomQA0AvNaeY/TTxQoXANN0/vSFsdWJvEtFombOgA4nEkoAzhqbkMqUAR1dNoon0iZeH0yWA70rInSHwogB65/OMMEn92JIpBwtMBwXNjPr5/20q8hKhGD96ng55R1GILwIaEVm76IqiDQiOxOkRzEwJkDLGlvcJIcePY8bE/vwrNbPjPoEGI1t1rcIzC4MDMYiMDFLtP/098RQL6VkMkOfVs6nnR2J43GclVxvMGa9+REyPJQaApOTFTjK06lhPx8Aly7Ym4fXgALeJBkr2BaUiXHLUYmiRqHZiyxi29O64gaE1CO6ZT0uceRqtJgU6Cibt7IUbErPJb5Dvy4DswrBnk568kXoYL6APqqnl6L15jgcLieIli/xNJSumsf+ANa5hWV2ZolAi9Bqf9AQSp4uy8LdtR2J4gKe44/Mwzi5fReVQmW6eKN88B4xWfnQ6B732DXEzDmSKjw8mhuOB3NrQf4tM6VncRLn1FF/lKoxXPwrnrw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: support-external-dns
      namespace: external-dns
