---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: support-external-dns
  namespace: external-dns
spec:
  encryptedData:
    pihole_password: AgBlNUWcKLKkFZk3ge+12GcwU4QDPNwLzsJM2pTaJfh60+fkiSd6abJ/ggrnCIQU9uzTPVKLy9Hj1M20IYb3J7cD716gzipYPzuhStPZ0BL/Y21QAcSCS6QR/IRtiiqLIkN1NAlBSkenbjA5QhW1FB621cGlhLHYQ74+zcE7YbfL+wUboGkxbf5BrlyhyYWODD9HlaK10j5PUuKJ6ok0qcFy8+mRAbMAMay8FsU9xo4o11mtrNElAHSXM7Z6lbKoITRgVS4XH1Y8iwNR4INeQ5w/OABMDhQjy0gdIJ5ukFAYWMa0lN4Y/4f68v4pjlC9YKbkpZJ25x/iGY0usQWvPp0+XAYUkI/BH69jrkOyB/4kBzdh/nisUydujUErtfuh5Q/vAGFfyk9WLHIGmgtK5bmTvDbWsLTTOvsSmQB0VB8jPIDNnh+Oaamzj8hf32zLuQOA0vgUiwe3a0bsdG+roGvARW17c9rmlg3CZey201jkO5SKPQjHkMHe4VgZHCGeN+21DaG3legKCVTMfG2xZVzrUN8mnk5Ar9IsNcs8x3e6e7+V5ZKaL49MVq6H+fmhQxZL89vMriKRjgRskpz+N1+Q8aAAI5DRiMmN+24347+hDvrCDZN9VWI1IQ7N6oTAwLMJu2+nbr+Dwqf9rkM5nQyHlL9+GYvEmqaYIzxcRBVSCqN6ieUA/+RamnHux4vMr3rZHhB0pc1sCXtgINDeKPIwrfOYHyJZ2fTzw5++amECgxhkfQHdqqe+bK5D0Py1yVv621UPXXqL/f7ygDd2ZHVHBg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: support-external-dns
      namespace: external-dns
