---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: support-external-dns
  namespace: external-dns
spec:
  encryptedData:
    pihole_password: AgCA4p6CQCtS781Y5F4A5vJnsrLeqAWWjE97HaJ3lF7PQ76PLx3xbro7F0msMZfiX8vTTz77OTVmQwT2L5/6FTj+5uzKpgj3CENFKpdUO9WDCCvec2yNDq3ttbpWM3hm0qN+32ENJoT1Ht+Z6efkW1ApZdfsk1iLBrXV1YzHQ/sm3tMu8G/qprHRbnayBDL+91CMpLKUzr40O9/sw5EEPp2WV/QsjGs/3UO3wKf8ip3flaIgv8qd5vrDxekYktKsV/bgpbQpTNTcN5o7a46DVt3VyNXBeieSRVJKmytEqKAm2iKgzxgagLnYgEeSQX+OIpcWktyvmLsZfh+z9zNUtAhq3cy80I5k1zTZWwB/oFass1JVvcWaZI0ZgD+eL2MejsfmtJAskqVVAP2FeEOqXCSTJDX7bNVVr039qgIkaN4OWaXFamXkvCGsCmKcXzaocg5xXmXF3CIWgdd2uZDO5fb8VJMg30YTJ6nROw8d7Spt63IriZfowRnfPc0V3eA91nM9C3S2EPD1ztkyM5T/KGqpqZXelophrppCI2YINUItNXGrIZgGxsOImrM7vMWsq5BNj38EcVPBs+X4RQF1s6d4RtFY1uXdeOx0CWSVmVsbkn2xAMnyEjSyrqUb1jszU5F2pvLdjFomev2DYTD4lH34Q6+b8z5dxMqwNjmZY9Cn9D+vGGWL7hxfT7xEMdCc0ZAi+Ff4YQJgLRHo0A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: support-external-dns
      namespace: external-dns
