apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homepage
# resources:
#   - secrets

helmCharts:
  - name: flame
    version: 0.6.0
    repo: https://charts.gabe565.com
    valuesFile: values.yaml
    namespace: homepage
    releaseName: services
