apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: support
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure declarative config for support
  destinations:
    - namespace: "*"
      server: "*"
    # - namespace: externaldns
    #   server: https://kubernetes.default.svc
    # - namespace: certmanager
    #   server: https://kubernetes.default.svc
    # - namespace: keel
    #   server: https://kubernetes.default.svc
    # - namespace: kube-system
    #   server: https://kubernetes.default.svc
    # - namespace: kubeseal
    #   server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
    # - "git@github.com:vancycles-industries/infrastructure.git"
  sourceNamespaces:
    - "*"
    # - "externaldns"
    # - "certmanager"
    # - "keel"
    # - "kube-system"
    # - "kubeseal" # for sealed secrets
