apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-leases-role
  namespace: kube-system
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create", "update", "patch"]
