apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-leases-rolebinding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: support-cert-manager
  namespace: certmanager
roleRef:
  kind: Role
  name: cert-manager-leases-role
  apiGroup: rbac.authorization.k8s.io
