# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-cluster-issuer-non-prod
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     email: henri-vandersleyen@protonmail.com
#     privateKeySecretRef:
#       name: letsencrypt-secret-non-prod
#     solvers:
#       # - dns01:
#       #     cloudflare:
#       #       apiTokenSecretRef:
#       #         name: cert-manager-secret
#       #         key: api-token
#       - http01:
#           ingress:
#             class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-namecheap
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-email@example.com
    privateKeySecretRef:
      name: namecheap-credentials
    solvers:
    - dns01:
        webhook:
          groupName: acme.vandersleyen.dev
          solverName: namecheap
          config:
            apiKeySecretRef:
              name: namecheap-credentials
              key: apiKey
            apiUserSecretRef:
              name: namecheap-credentials
              key: apiUser
            clientIpSecretRef:
              name: namecheap-credentials
              key: clientIp
            # production: true
