apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer-non-prod
spec:
  acme:
    email: henri-vandersleyen@protonmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-secret-non-prod
    solvers:
      - http01:
          ingress:
            class: nginx
