[[language]]
name = "python"
roots = ["pyproject.toml"]
formatter = { command = "black", args = ["--quiet", "-"] }
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {} 
auto-format = true

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkg fmt" }
language-server = { command = "nil" }

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "go"
auto-format = true
language-server = { command = "gopls" }

[[language]]
name = "yaml"
file-types = ["yml", "yaml"]
indent = { tab-width = 2, unit = "  " }
language-servers = [ "yaml-language-server" ]
auto-format = true
# language-server = { command = "gopls" }

[[language]]
name = "hcl"
indent = { tab-width = 2, unit = "  " }
language-servers = [ "terraform-ls" ]
auto-format = true

[[language]]
name = "toml"
injection-regex = "toml"
file-types = ["toml", "poetry.lock", "Cargo.lock"]
roots = []
comment-token = "#"
language-servers = [ "taplo" ]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "typescript"
injection-regex = "(ts|typescript)"
file-types = ["ts", "mts", "cts"]
language-id = "typescript"
roots = []
# pass format options according to https://github.com/typescript-language-server/typescript-language-server#workspacedidchangeconfiguration omitting the "[language].format." prefix.
config = { format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = true } }
language-servers = [ "typescript-language-server" ]
auto-format = true

[[language]]
name = "javascript"
injection-regex = "(js|javascript)"
language-id = "javascript"
file-types = ["js", "mjs", "cjs"]
#shebangs = ["node"]
comment-token = "//"
language-servers = [ "typescript-language-server" ]
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "json"
scope = "source.json"
injection-regex = "json"
file-types = ["json", "jsonc", "arb", "ipynb", "geojson"]
roots = []
language-servers = [ "vscode-json-language-server" ]
auto-format = true
indent = { tab-width = 2, unit = "  " }