[[language]]
name = "python"
roots = ["pyproject.toml"]
formatter = { command = "black", args = ["--quiet", "-"] }
#language-servers = [{ command = "pyright-langserver", args = ["--stdio"] }]
# config = {} 
auto-format = true

[[language]]
name = "common-lisp"
auto-format = true
formatter = { command = "cl-lisp" }
#language-servers = [{ command = "nil" }]

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkg fmt" }
#language-servers = { command = "nil" }

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "go"
auto-format = true
#language-servers = { command = "gopls" }

[[language]]
name = "yaml"
file-types = ["yml", "yaml"]
indent = { tab-width = 2, unit = "  " }
#language-servers = { command =  "yaml-language-server" }
auto-format = true
# language-server = { command = "gopls" }

[[language]]
name = "hcl"
indent = { tab-width = 2, unit = "  " }
#language-servers = { command = "terraform-ls" }
auto-format = true

[[language]]
name = "toml"
injection-regex = "toml"
file-types = ["toml", "poetry.lock", "Cargo.lock"]
comment-token = "#"
#language-servers = { command = "taplo" }
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "typescript"
injection-regex = "(ts|typescript)"
file-types = ["ts", "mts", "cts"]
roots = []
# pass format options according to https://github.com/typescript-language-server/typescript-language-server#workspacedidchangeconfiguration omitting the "[language].format." prefix.
# config = { format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = true } }
#language-servers = { command =  "typescript-language-server" }
auto-format = true

[[language]]
name = "javascript"
injection-regex = "(js|javascript)"
file-types = ["js", "mjs", "cjs"]
#shebangs = ["node"]
comment-token = "//"
#language-servers = { command =  "typescript-language-server" }
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "json"
scope = "source.json"
injection-regex = "json"
file-types = ["json", "jsonc", "arb", "ipynb", "geojson"]
roots = []
#language-servers = { command =  "vscode-json-language-server" }
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "svelte"
injection-regex = "svelte"
file-types = ["svelte"]
roots = []
indent = { tab-width = 2, unit = "  " }
#language-servers = { command =  "svelte-language-server" }
auto-format = true

[[language]]
name = "lua"
injection-regex = "lua"
file-types = ["lua"]
shebangs = ["lua"]
roots = [".luarc.json", ".luacheckrc", ".stylua.toml", "selene.toml", ".git"]
comment-token = "--"
indent = { tab-width = 2, unit = "  " }
#language-servers = { command = "lua-language-server" }
formatter = { command = "LuaFormatter"}
auto-format = true
