apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeseal

resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.27.1/controller.yaml
# Controller isn't created for some reason
# helmCharts:
# - name: sealed-secrets
#   version: 2.9.0
#   repo: https://bitnami-labs.github.io/sealed-secrets/
#   valuesFile: values.yaml
#   namespace: secrets
#   releaseName: sealed-secrets
