apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: nix-k8s-homelab/charts/monitoring/prometheus-graphana/overlays/prod
    target:
      kind: Application
      name: prometheus-graphana
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: nix-k8s-homelab/charts/monitoring/loki/overlays/prod
    target:
      kind: Application
      name: loki
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: nix-k8s-homelab/charts/monitoring/tempo/overlays/prod
    target:
      kind: Application
      name: tempo
  - patch: |-
      - op: replace
        path: /spec/source/repoURL
        value: git@github.com:Vanderscycle/dotFiles.git
    target:
      kind: Application
      name: .*
